### ISSUE TITLE
[prod] Error: Queue limit reached

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-db-mysql#10]
At about 2015-02-11T13:36Z, across all production fxa-auth-db servers, there were hundreds of 500 errors with this stack. I don't really have more information at this time. Things we need to look at are stackdriver/cloudwatch mysql stats; `show engine innodb status` on prod.

Error: Queue limit reached.
    at Pool.getConnection (/data/fxa-auth-db-server/node_modules/mysql/lib/Pool.js:64:15)
    at PoolCluster._getConnection (/data/fxa-auth-db-server/node_modules/mysql/lib/PoolCluster.js:148:13)
    at PoolNamespace.getConnection (/data/fxa-auth-db-server/node_modules/mysql/lib/PoolCluster.js:188:17)
    at PoolCluster.getConnection (/data/fxa-auth-db-server/node_modules/mysql/lib/PoolCluster.js:80:13)
    at promisified (eval at makeNodePromisifiedEval (/data/fxa-auth-db-server/node_modules/bluebird/js/main/promisify.js:195:12), <anonymous>:2:343)
    at retryable (/data/fxa-auth-db-server/db/mysql.js:636:12)
    at MySql.getConnection (/data/fxa-auth-db-server/db/mysql.js:605:12)
    at MySql.singleQuery (/data/fxa-auth-db-server/db/mysql.js:490:17)
    at MySql.read (/data/fxa-auth-db-server/db/mysql.js:575:17)
    at MySql.readFirstResult (/data/fxa-auth-db-server/db/mysql.js:556:17)

**Comment by chilts** [comment]
Yeah, something is slightly strange here in that it's perhaps coming from the `retryable()` function in the mysql.js file. ie. is something failing, then being retried (and failing again and then being retried ...).

@jrgm is there any error in the mysql logs to show the root cause problem? Also, is this carrying on now, was it a one off or is it intermittent?

**Comment by chilts** [comment]
Just a clarification about repos to future readers. Since the current prod stack is running the non-reverse backend db-server, this issue is related to the fxa-auth-db-server, however it's this repo that'll probably need the fix (and perhaps the latest train branch in fxa-auth-db-server).

**Comment by chilts** [comment]
@jrgm: what is the config.master.queueLimit set to in prod?

**Comment by jrgm** [comment]
Prod settings would be like:

```
  "master": {
        "user": "USER",
        "password": "PASS",
        "database": "fxa",
        "host": "HOST",
        "port": PORT,
        "connectionLimit": 20,
        "waitForConnections": true,
        "queueLimit": 100
    },
```

**Comment by jrgm** [comment]
> @jrgm is there any error in the mysql logs to show the root cause problem? 

I need to ask @ckolos to get that info from RDS in prod.

> Also, is this carrying on now, was it a one off or is it intermittent?

One off

**Comment by ckolos** [comment]
There's nothing in the rds logs except for a small number of ( < 20) getaddr errors

**Comment by chilts** [comment]
@jrgm could this be similar to what we saw last week but manifested in a different way. We keep getting lots of request, but one (per mysql connection) stalls somehow. Others get queued behind, reaches 100 and we start seeing errors in the db-server logs - though mysql doesn't see that anything is wrong. Just thinking out loud.

**Comment by jrgm** [comment]
Yeah, so I was thinking it was some thing like that, but we don't have data to know. (At a previous job, we had a minutely cronjob doing `mysql -uUSER -pPASS -e 'show full processlist' > /var/log/mysqlproclist/`date +%H%M`. You could find lots of interesting transient bugs this way ;-) ).

**Comment by rfk** [comment]
Is there much more we can do with this bug?  It sounds like we need better visibility into the state of the db to get a real handle on what's going on.

**Comment by jrgm** [comment]
NOthing really to do here. We don't hit this commonly enough to be a problem.
