### ISSUE TITLE
Update mozlog dependency to 2.0.2 or greater

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-db-mysql#103]
It's got a few cleanups and improved error handling.

**Comment by vladikoff** [comment]
cc @dannycoates

**Comment by vladikoff** [comment]
from mtg: was rolled back, will need to be updated again

**Comment by jrgm** [comment]
Well, not rolled back in the source repo. But train-48 was rolled back to train-47 in production due to a leak.

**Comment by vladikoff** [comment]
@jrgm do we have an issue for that leak problem? 

Otherwise thanks for explaining, as it is in the source that means this is done!
