### ISSUE TITLE
Device support

### ISSUE THREAD

**Issue by dannycoates** [mozilla/fxa-auth-db-mysql#104]
DB support for device API: https://gist.github.com/dannycoates/44b1965a6be42060e15f

- [ ] new device endpoints
- [ ] update account endpoints and stored procedures
- [ ] new device table and stored procedures

**Comment by rfk** [comment]
@dannycoates I have vague recollection of you mentioning that you wanted to get this in train-48, adding "shipit" so we remember to revisit tomorrow
