### ISSUE TITLE
db connections must reconnect on multi-az RDS failover

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-db-mysql#109]
With Multi-AZ RDS Failover, from a client connection view, what will happen is that the current master database will shut down, terminating the TCP connection, then DNS will propagate a new IP for the (new) master db, and the database connection should reconnect.

In my tests in stage, under load, this only happened once in 4 tries. 

I can provide further details, setup assistance as needed.

This should be a priority to fix to ensure minimal downtime.

**Comment by rfk** [comment]
Dup of #108
