### ISSUE TITLE
Drop old stored procedures

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-db-mysql#111]
I'm not certain that all of these are okay for retirement but a peek at my local database shows the following stored procedures have newer versions:
- `account_2`
- `createAccount_2`
- `createSessionToken_1`
- `deleteAccount_4`
- `emailRecord_2`
- `passwordChangeToken_1`
- `sessionToken_1`
- `sessionToken_2`

**Comment by vladikoff** [comment]
backlog!

**Comment by vladikoff** [comment]
from mtg with @jrgm: 

in prod / stage: not important to get rid of them
in dev: unless there is a specific reason why (hard to find procedures and scroll through the list?) we should probably just leave it alone to avoid causing more issues, especially with deploys.
