### ISSUE TITLE
Leak in train-48

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-db-mysql#113]
re: https://bugzilla.mozilla.org/show_bug.cgi?id=1220397

There is a significant leak in train-48 in the auth-db-server, which required us to rollback to train-47 version of auth-db/auth.

I don't see a leak in the actual changes in train-48. I set up some some branches where I undid the module version updates, then selectively updated each separately and ran some load tests. There is noise in these numbers, but the update to bluebird (and how we use it?) looks to be a good candidate as to what is doing (most of?) the leaking.

```
                                          RSS end        Pct. change             RSS post        Pct. change
                                          of test                               forced GC

48-no-module-updates-#1 (10min)             89412               1.0%                74188               6.6%
48-no-module-updates-#2 (10min)             89780               1.5%                68896              -1.0%
48-no-module-updates-#3 (10min)             86268              -2.5%                65756              -5.5%
48-no-module-updates-average                88487               0.0%                69613               0.0%
train-46 (10min)                            89110               0.7%                71564               2.8%
48 update clone,convict,mozlog (10min)      89232               0.8%                68728              -1.3%
48 update only bluebird (10min)             93520               5.7%                74820               7.5%
48 update only fxa-jwtool (10min)           90984               2.8%                71076               2.1%
48 update only mysql (10min)                96404               8.9%                71124               2.2%
48 update only request (10min)              91404               3.3%                68968              -0.9%
48 update only restify (10min)              91760               3.7%                68804              -1.2%
48 update only mysql (1hr)                  93360               5.5%                72516               4.2%
48 update all except mysql (1hr)           111764              26.3%                87728              26.0%
48 update only bluebird (1hr)              112016              26.6%                87256              25.3%
48 update all except bluebird (1hr)         96792               9.4%                72652               4.4%
```

Not sure how to proceed further in isolating the root cause of the leak. @dannycoates?

**Comment by vladikoff** [comment]
First look at this, I could not reproduce the leak locally 

The most memory usage I got was:

![](http://v14d.com/i/563846601bc98.jpg)

Ref https://github.com/SalesforceEng/tough-cookie/issues/48

I was testing in node 0.12 though because v8 profiling does not work well in 0.10.

**Comment by jrgm** [comment]
@dannycoates to revert module changes, except updates for convict and mozlog for train-49 in the interim.d

**Comment by vladikoff** [comment]
cc @dannycoates ping

**Comment by vladikoff** [comment]
@dannycoates how were you able to reproduce the leak?

**Comment by vladikoff** [comment]
@jrgm does this still happen?

**Comment by jrgm** [comment]
No. We seem to have cured it with an upgrade.
