### ISSUE TITLE
Store public key for push endpoint in the devices table

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-db-mysql#114]
See:

* https://developer.mozilla.org/en-US/docs/Web/API/Push_API/Using_the_Push_API#Technology_overview

* https://developer.mozilla.org/en-US/docs/Web/API/PushSubscription/getKey

* https://tools.ietf.org/html/draft-ietf-webpush-encryption-01

**Comment by kitcambridge** [comment]
Yup, these are the right building blocks! Here's a Node library for encrypting the message on the server, too: https://github.com/marco-c/web-push
