### ISSUE TITLE
Be consistent about how timestamps are generated

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-db-mysql#12]
While digging to our use of the `verifierSetAt` field, I noticed that at account-creation time we explicitly pass in a timestamp from the auth-server:

  https://github.com/mozilla/fxa-auth-db-mysql/blob/master/db/mysql.js#L177

While at account-reset time we allow the auth-db-server to generate its own timestamp:

  https://github.com/mozilla/fxa-auth-db-mysql/blob/master/db/mysql.js#L425

It's likely nothing bad will come of this, but we should probably be consistent.  My vote would be to pass in all timestamps from the auth-server since that's what we're already doing in the majority of cases.

**Comment by jrgm** [comment]
Actually, should update/insert/replace statements be accepting values of javascript values of `Date.now()` when they could just be using the database servers monotonic value of `NOW()`?

**Comment by jrgm** [comment]
(I meant `UNIX_TIMESTAMP()*1000`, not `NOW()` above. The point being that we have multiple servers in production that try to be close in time, but can diverge; why not just let the db server use its clock).

**Comment by chilts** [comment]
I think the initial idea about all of this is that there is no logic in the datastore (MySql or otherwise) and that it's the auth server which has the smarts, even the DB server is dumb. @dannycoates may be able to enlighten some more.

**Comment by rfk** [comment]
FWIW I don't fell strongly either way, but we should be consistent.

**Comment by dannycoates** [comment]
Hmm, where should the burden of keeping time synced go? Ideally all the computers should be in sync so it shouldn't matter, but I think logically (as opposed to physically) it'd be nice if the app layer could tolerate out of sync clocks. On the other hand the app already has to deal with time in other areas (certs, hawk, token expiry) that interact with "db time" and it would be annoying to have to ask a lower level, "What time is it?" all the... time.

In light of our current use of time I think its best to do timestamping at the app layer and try really hard to keep those clocks in sync.

**Comment by chilts** [comment]
Both the mysql/mem backends set defaults for these fields:

* .createAccount() - createdAt, verifierSetAt, normalizedEmail

All of these fields are already set in the auth server. These can just be taken out.

However, both the mysql/mem backends also set a default for this field:

* .resetAccount() - verifierSetAt

But, the auth server does not set this in the accountResetToken passed to `.resetAccount()` in both the `/account/reset` or `/password/change/finish` routes. That'll need to be updated first, then this can be taken out as well.
