### ISSUE TITLE
db migration for push key formats can't be deployed in production

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-db-mysql#135]
/cc @eoger @jrgm; from https://github.com/mozilla/fxa-auth-db-mysql/pull/133#discussion_r62130229

In #133 we added a database migration that changes the column type for push callback pubkeys.  @jrgm notes that it can't be deployed in production due to the change on the column type causing errors.  We need to figure out a way forward for this before cutting train-62.

I'm hopeful that we can get around it by deploying two migrations - one that drops the pubkey stuff entirely and updates stored procedures to not reference that column at all, and a second that adds the pubkey stuff back in in the new format.

@jrgm does this sound like a reasonable approach to the problems you saw?

**Comment by vladikoff** [comment]
I think @jbuck also had a few idea on this....

**Comment by rfk** [comment]
I removed "blocker" from this as it sounds like we may be able to land to original patch after all, but let's keep the PRs around until that's successfully in production.

**Comment by vladikoff** [comment]
> can't be deployed in production

but @jrgm and @jbuck did it! 🎆
