### ISSUE TITLE
npm shrinkwrap is out of date on train-31

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-db-mysql#14]
I noticed that a Kibana graph of auth-db errors (that only runs in production, not stage) had stopped updating with the release. I chatted with @whd and it was because the log lines were missing an HTTP 'code' value. After much digging and head scratching, the root cause is that the `npm-shrinkwrap.json` file in `fxa-auth-db-mysql` is specifically pinned to a git SHA in https://github.com/mozilla/fxa-auth-db-mysql/blob/train-31/npm-shrinkwrap.json#L286-L290. This obviously is pretty disturbing, and we can talk later about how to prevent this from occuring (i.e., tools to validate that package.json, node_modules and npm-shrinkwrap.json are in sync, and a grunt task that will consistently maintain `npm-shrinkwrap.json`).

However, the "good" news is that the only actual code change that was dropped was [this change](https://github.com/mozilla/fxa-auth-db-server/commit/aa0b6d484a6965d2c25ea02062dc7a4290366af0), which is why the log line in production was missing.

I considered asking @ckolos to rollback to train-30 on auth-server, but have decided that the missing log line is "liveable". I think we should pick up the L10N strings and a fix for train-31 npm-shrinkwrap to get back to where we should be, and I'll work on that now.

**Comment by jrgm** [comment]
Sorry, I forgot to add "if anyone feels that we should rollback for the logging bug, let me @ckolos know".

**Comment by rfk** [comment]
Ugh.  I like the idea of shrinkwrap in principle, but man, it's a PITA in practice...

> we can talk later about how to prevent this from occuring (i.e., tools to validate that package.json,
> node_modules and npm-shrinkwrap.json are in sync, and a grunt task that will consistently maintain
> npm-shrinkwrap.json).

One idea may be to remove npm-shrinkwrap.json from master, explicitly generate it for each release and only commit it on the branch.

**Comment by chilts** [comment]
Yes, we certainly need a procedure somewhere (Grunt or otherwise) which goes through all the things we need to do each release. I think I mentioned elsewhere too that if we are using Git ref-specs for package.json things, we should stick to branch names and not hashes.

**Comment by jrgm** [comment]
I've been trying out [uber/npm-shrinkwrap](https://github.com/uber/npm-shrinkwrap/blob/master/README.md) and despite some quirky behaviours, like it looks like it would be useful in getting some consistency in the way we use shrinkwrap (especially the ordering and `from`-churn). But, there are though some problems I see with using it as-is.

- it's based on npm@1.4.21, which in dog/npm years is ancient (ahh, fall 2014). I tried updating it's module deps though and it seems to work with npm 2.6.

- it's insistent that git url's use `semver` for tags (i.e., no #train-31 or #9a8b7c6e fragments allowed). I think it wouldn't be hard to teach it how to check the `resolved` value in npm-installed package.json.

- there's an open issue to implement a `--check` option to just ensure that package.json, npm-shrinkwrap.json and ./node_modules are consistent. That would be a good thing to add.

**Comment by jrgm** [comment]
I'll close this now.
