### ISSUE TITLE
Is PUT /accountResetToken/:id ever hit?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-db-mysql#150]
Over in https://github.com/mozilla/fxa-auth-server/pull/1384, we're removing `createAccountResetToken` because it is never called, `forgotPasswordVerified` is instead.

Both those methods map to separate endpoints and stored procedures in this repo. Should we remove the `PUT /accountResetToken/:id` endpoint and the `createAccountResetToken` stored procedure on the basis that the auth server never calls them?

**Comment by philbooth** [comment]
Fwiw, I had a look at this in Kibana and couldn't see any requests. But it's also possible that I was using Kibana wrong, I'm quite ham-fisted when it comes to interrogating the query/filter input field it has.

**Comment by rfk** [comment]
I couldn't find any either; FWIW here's no attempt at a dashboard showing plenty of gets, but no puts: https://kibana.fxa.us-west-2.prod.mozaws.net/#dashboard/temp/AVZKbfNgayLd6KaGw-mu
