### ISSUE TITLE
Add a third token state to unverifiedTokens

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-db-mysql#151]
Arising from the discussion at https://github.com/mozilla/fxa-auth-server/issues/1374#issuecomment-236054391, it has become clear that the binary state modelled by `unverifiedTokens` is insufficient. Specifically, there is a class of tokens for which we would like to say "this token hasn't been verified and doesn't need to be".

@rfk suggested we could use a `NULL` in the `tokenVerificationId` column to imply the state. Alternatively, if we didn't fancy implying the state in that way, a migration to add an extra column should be quite quick to execute because records are expunged from that table as tokens get verified.

**Comment by philbooth** [comment]
Also see https://github.com/mozilla/fxa-auth-server/pull/1376.

**Comment by vbudhram** [comment]
This is also related to this auth server issue https://github.com/mozilla/fxa-auth-server/issues/1367, different from above referenced one.

**Comment by rfk** [comment]
> we didn't fancy implying the state in that way

When you put it like that, "implying state" sounds a bad idea, and a separate column will probably be clearer and simpler :-)
