### ISSUE TITLE
Can we eliminate two frequent sources of programmer error?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-db-mysql#157]
I woke up thinking about [this PR comment](https://github.com/mozilla/fxa-auth-db-mysql/pull/155#issuecomment-239049101):

> Thanks for a keen eye

The thing is, a keen eye had nothing to do with it. The reason I spotted those oversights was because I specifically looked for them. And the reason I specifically looked for them was because I make the exact same oversights every single time I write a new migration. I don't think this is a coincidence.

The two oversights are:
1. Forgetting to update every point in the documentation that mentions the thing you're changing.
2. Using the wrong patch level in the rollback migration.
## The docs

The docs are really long. Using marks and split windows in vim makes them a bit more navigable but its still easy to lose track of where you are or where related sections are.

They also repeat themselves. Every section looks identical at a glance, so it's really easy to scroll past the end of the section you're supposed to be working on and start editing the wrong bit. I do this a lot.

The two documents for the server API and the database API express identical information for different layers. It's really easy to remember to update one of them but not the other. This is exacerbated by them living in different directories; it's too easy not to notice that you forgot to edit one.

Some ideas:
- We should break the docs down into a more hierarchical structure. One for each table in the db doc, one for each base path in the server doc.
- We should have a top-level doc for each (db and server) that tries to establish some of the common boilerplate so that individual sections can be shorter. Not sure how doable this is in practice, things like the full JSON response body and the full curl incantation have value for the reader.
- The db and server docs should live side-by-side in the same directory. It would be harder to forget one but not the other then.
- Would it be easier to maintain the db doc if it was generated from jsdoc comments? Maybe people are more likely to remember to update them as they're right there in the same bit of code that you have to edit.
## The rollback migration

There is no automation around applying and testing the rollback migration, so it is really easy to leave copy-paste errors behind. Especially the patch level, but also to a lesser extent stored procedure versions.

The easiest way to create this migration is copy-pasting an old one to use as a template. Then you make your changes and use MySQL Workbench to make sure that it applies cleanly and the database seems correct with it applied. But you can't (easily) run the tests against it at this point because they and all of the code still expect the db to be in the pre-rollback state. So you tell yourself it looks okay and there's a code review that will double-check it for you.

Some ideas:
- Maybe this isn't enough of a problem to actually fix? Have we ever used a rollback migration? In the event of needing to rollback the db, would these errors be obvious to the roller-backer?
- We could write a script that generates the skeleton rollback migration based on the one it rolls back. A `DROP` for every `CREATE` etc and the correct patch level. It wouldn't be able to write a complete migration (unless we introduced some serious logic that went through all the migrations looking for earlier versions of stored procedures etc), but it would be enough of a start to avoid the common pitfalls.
- Would it be possible to automate some kind of test that applies your migration to `master`, then applies the rollback migration, then runs the tests in `master` to make sure they all still work?

**Comment by vbudhram** [comment]
I have definitely been hit by the docs and migration issues you raised. I like the solutions you proposed for the docs, although, if I were to pick, I would probably prefer having the docs live more closely together (same project). In the case of auth, maybe all docs live in the auth-server, you will always have to update the version of fxa-mysql in the auth-server anyways?

Using a jsdoc comment block and automating documentation is another good proposal. Although, I think the trap I typically fall into is forgetting to update the comment block more so than updating a document.

Something I found helpful in the past is to have an explicit task list in the PR and have one of those items be update docs.

For database migrations and rollbacks, not sure how to best handle that. The procedure you described is pretty much the same way I test it. I like the idea of using a script to generate migration/rollback files. [Sequelize](http://docs.sequelizejs.com/en/latest/docs/migrations/) does  something similar through their CLI with `sequelize migration:create`.

**Comment by philbooth** [comment]
> In the case of auth, maybe all docs live in the auth-server, you will always have to update the version of fxa-mysql in the auth-server anyways?

I may have misread your comment, apologies if so, but it's not an auth-server / auth-db duality that vexes me. Everything is inside this repo.

Essentially, for the docs part, these two should live closer and have duplication removed:

* db: https://github.com/mozilla/fxa-auth-db-mysql/blob/master/docs/API.md
* server: https://github.com/mozilla/fxa-auth-db-mysql/blob/master/fxa-auth-db-server/docs/API.md

(same repo)

**Comment by philbooth** [comment]
Returning this to the backlog until we have time for it.

**Comment by philbooth** [comment]
Closing in favour of #202.
