### ISSUE TITLE
Should we enforce device <=> sessionToken parity?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-db-mysql#162]
This question arises from discussion about the following query from #160 (later removed):

```sql
-- Prior to this migration, it was possible to delete a session token
-- without deleting the associated device (if a device record exists).
-- That's fixed by deleteSessionTokens_3, but we should also purge any
-- historical devices that have reached this state.
DELETE FROM devices
  USING devices LEFT JOIN sessionTokens
    ON devices.sessionTokenId = sessionTokens.tokenId
  WHERE sessionTokens.tokenId IS NULL;
```

Leaving aside the unresolved question of whether it is feasible to run against the production database, it is only worth doing if we can sanely enforce the existence of a session token for every device record.

Based on eyeballing the stored procedures and testing assorted connection and disconnection methods, I think we can enforce that. The related problem described in mozilla/fxa-content-server#4060 doesn't affect the parity because both the session token and the device are left in the database in that case.

Whether we want to enforce any parity is another matter. In addition to any cost of running the above query to delete zombies, there is the cost of adding a new constraint to the `devices` table in the production database. Hence opening this issue as a question.

**Comment by philbooth** [comment]
Forgot to mention, I started to investigate the unresolved question of query performance but got stuck because Python (I was trying to use the auth server load-testing stuff).

Have started to roll my own load-testing script instead, will add it to this repo when its ready.

**Comment by vbudhram** [comment]
mtg: @rfk @philbooth to set priority

**Comment by rfk** [comment]
> there is the cost of adding a new constraint to the devices table in the production database

I'm gently -1 on adding an explicit DB constraint, but what we could do is update the `accountDevices` query to ensure that we don't report invalid sessionTokenIds.  Currently it's like this:

```
BEGIN
  SELECT
    d.uid,
    d.id,
    d.sessionTokenId,
   [...]
    s.uaBrowser,
    s.lastAccessTime
  FROM
    devices d LEFT JOIN sessionTokens s
  ON
    d.sessionTokenId = s.tokenId
  WHERE
    d.uid = inUid;
END;
```

So if the device does has a sessionTokenId that's not longer in the database, it's still returned by the query.  We could change the query here to return `s.tokenId` rather than `d.sessionTokenId`, so that if we *have* somehow left device records pointing to an invalid sessionToken, at least they show up in case as `d.sessionTokenId === null`.

**Comment by philbooth** [comment]
> We could change the query here to return `s.tokenId` rather than `d.sessionTokenId`, so that if we *have* somehow left device records pointing to an invalid sessionToken, at least they show up in case as `d.sessionTokenId === null`.

Good point, I hadn't considered the possibility of leaving the zombie devices in place and ignoring them. Or we could even switch the query to an `INNER JOIN` and just not return them at all?

The only consumers of the result set are the devices view and the push notifications, neither of which needs to process items that we know there is no session for. And they probably don't want the burden of filtering out spurious items either.

Fwiw, I took the precaution of testing out `INNER JOIN` vs `LEFT JOIN` locally (because tripping over MySQL performance gotchas is my special talent). With the obvious proviso about it not being production-scale (~10 million accounts, ~15 million session tokens, ~7.5 million devices), the difference was in the order of tens of milliseconds on a ~4 second query (used medians from 5 runs).
