### ISSUE TITLE
Run auth-server tests on PR before merge

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-db-mysql#186]
Open discussion on if we should run a suite of auth-server tests on the version of fxa-auth-db-mysql PR being committed. It could be used to help detect errors that might happen downstream (ref https://github.com/mozilla/fxa-auth-db-mysql/issues/183). This is similar to the  proposed auth-server/content-server https://github.com/mozilla/fxa-auth-server/issues/1544.

**Comment by vladikoff** [comment]
should probably run test/remote...

**Comment by philbooth** [comment]
Should we just merge the two repos? It would make testing so much easier and it would also help with situations like the dependency that arose between #259 and mozilla/fxa-auth-server#1986.

We managed the merge process pretty easily with the auth mailer, so I don't see much of a case for keeping this one separate. Am I missing anything?

**Comment by philbooth** [comment]
> Should we just merge the two repos?

Another argument in favour:

https://github.com/mozilla/fxa-auth-server/blob/5742ffff3ab57f3af2c0dbd1aa70087d27efe0a9/lib/db.js#L998-L1019

We could `require` those error definitions directly instead of hard-coding them.

**Comment by rfk** [comment]
> Should we just merge the two repos?

On the other hand, I believe we'd still *eventually* like to be in a place where we're running the DB code on a separate box to the auth-server, for various opsec reasons.  Merging the repos might make that a little harder.
