### ISSUE TITLE
Add an `npm run shrinkwrap` command

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-db-mysql#189]
Ref 
https://github.com/mozilla/fxa-content-server/issues/4439
https://github.com/mozilla/fxa-auth-server/issues/1564
https://github.com/mozilla/fxa-profile-server/issues/223

Example: https://github.com/mozilla/fxa-auth-mailer/blob/master/package.json#L10

**Comment by TDA** [comment]
@shane-tomlinson This repo already seems to have that. Can this be closed?

**Comment by vladikoff** [comment]
https://github.com/mozilla/fxa-content-server/pull/4445#discussion_r89481956
