### ISSUE TITLE
getConnection ignores "name" argument

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-db-mysql#19]
I was just perusing the code here:

  https://github.com/mozilla/fxa-auth-db-mysql/blob/master/db/mysql.js#L628

And AFAICT the `getConnection` method ignores its "name" argument.  Something doesn't seem right there.  @chilts can you please sanity-check this?

**Comment by chilts** [comment]
Yes, you're right, looks like it's not used. It wasn't brought over into the reverse backend branch.

Although wait, perhaps it was even before that. This is the last commit of the non-reverse fxa-auth-db-server, and it looks the same there : https://github.com/mozilla/fxa-auth-db-server/blob/c66640706752da860342291a4d531ee4e9f4cca0/db/mysql.js#L594-L599

So yeah, something is wrong, but perhaps it's not a recent introduction which was my first thought. I'll look some more tomorrow. Ta.
