### ISSUE TITLE
Running out of DB connections on fxa-dev boxes?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-db-mysql#194]
When running functional tests against fxa-ci we often see "Internal Server Error" in the test logs, which usually corresponds to an [app.Translate related error](https://github.com/mozilla/fxa-auth-server/issues/1553) in the auth-server logs.

Today when I ran the ansible script on fxa-ci, this error was reported (w/ host, user and password removed):

```
TASK: [sync | create syncserver database] *************************************
failed: [localhost] => {"changed": false, "cmd": ["mysql", "--host=XXX", "--user=XXX", "--password=XXX", "-e", "CREATE DATABASE IF NOT EXISTS sync"], "delta": "0:00:00.007519", "end": "2016-12-14 21:28:45.013063", "item": "", "rc": 1, "start": "2016-12-14 21:28:45.005544"}
stderr: ERROR 1040 (08004): Too many connections

FATAL: all hosts have already failed -- aborting
```

I tried several more times and kept seeing the same error. When I restarted the local fxa-auth-db-server, everything completed as expected.

Is the db-server holding open connections to the DB which would cause problems downstream?

**Comment by vladikoff** [comment]
stable and latest got more RDS connections! thanks to @jrgm
