### ISSUE TITLE
server holding open DB connections?

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-db-mysql#195]
Follow on from #194. @jrgm bumpted the number of RDS connections available to each box, but after a day or two of running, the circle tests start failing again, reporting `INTERNAL SERVER ERROR` in the auth-server logs:

> {"Timestamp":1482147312538000000,"Logger":"fxa-auth-server","Type":"request.summary","Severity":2,"Pid":10757,"EnvVersion":"2.0","Fields":{"op":"request.summary","code":500,"errno":999,"rid":"1482147312534:ip-172-31-44-29:10757:iwvz9xx3:10313","path":"/auth/v1/account/create","lang":"en-US,en;q=0.5","agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:40.0) Gecko/20100101 Firefox/40.0 FxATester/1.0","remoteAddressChain":"[\"52.15.215.173\",\"172.31.41.87\",\"127.0.0.1\"]","t":4,"uid":"00","email":"signin0.667042279150337@restmail.net","stack":"Error: Internal Server Error\n    at handleResponse (/data/fxa-auth-server/lib/pool.js:57:19)\n    at RequestSet.<anonymous> (/data/fxa-auth-server/node_modules/poolee/lib/pool.js:151:4)\n    at RequestSet.handleResponse (/data/fxa-auth-server/node_modules/poolee/lib/request_set.js:66:8)\n    at Endpoint.complete (/data/fxa-auth-server/node_modules/poolee/lib/endpoint.js:162:11)\n    at Endpoint.succeeded (/data/fxa-auth-server/node_modules/poolee/lib/endpoint.js:168:8)\n    at IncomingMessage.gotEnd (/data/fxa-auth-server/node_modules/poolee/lib/endpoint.js:326:8)\n    at emitNone (events.js:72:20)\n    at IncomingMessage.emit (events.js:166:7)\n    at endReadableNT (_stream_readable.js:923:12)\n    at nextTickCallbackWith2Args (node.js:458:9)\n    at process._tickDomainCallback (node.js:413:17)"}}

Problems go away as soon as I restart the auth-db server.

**Comment by shane-tomlinson** [comment]
Could this be the problem?

https://github.com/mozilla/fxa-auth-db-mysql/blob/1e3763dbe47a88c9ce41ee0796b2083c50b898c8/lib/db/mysql.js#L35:L46

>  // poolCluster will remove the pool after `removeNodeErrorCount` errors.
>  // We don't ever want to remove a pool because we only have one pool
>  // for writing and reading each. Connection errors are mostly out of our
>  // control for automatic recovery so monitoring of 503s is critical.
>  // Since `removeNodeErrorCount` is Infinity `canRetry` must be false
>  // to prevent inifinite retry attempts.

**Comment by rfk** [comment]
I *think* that logic is OK, but it may be worth-reverifying.  The relevant code in the `mysql` module that uses these settings, only deals with multiplexing between different connection pools, it doesn't handle any connections itself.

**Comment by shane-tomlinson** [comment]
Closing - this hasn't been happening recently since @vladikoff and @jrgm got together and fixed all the DB things.
