### ISSUE TITLE
Add an email bounces table

### ISSUE THREAD

**Issue by seanmonstar** [mozilla/fxa-auth-db-mysql#197]
We need a record of emails that have bounced. Our database has infinite size, right? Let's fill it up!

Proposed columns:

- email
- timestamp
- bounce type
- template
- language

**Comment by vladikoff** [comment]
@seanmonstar also see there is `bounceSubType` and `type` from here: https://kibana-fxa-us-west-2.prod.mozaws.net/#/dashboard/elasticsearch/Auth%20Bouncer%20Logs

**Comment by rfk** [comment]
It may also be worth differentiating "bounce" and "complaint" in the same way that SES does, so we've got as much data as possible when making decisions bout sendability.  Some notes here:

  https://github.com/mozilla/fxa-auth-server/issues/1565#issuecomment-271210096

(That issue also has an older proposed table schema, but I like @seanmonstar's idea of just recording each bounce/complaint event as an individual row)
