### ISSUE TITLE
Add dockerflow build logic

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-db-mysql#208]
Because we want to dockerflow all the things.

**Comment by vladikoff** [comment]
Hm does this have to be in docker or is this already include via fxa-auth-server?

**Comment by rfk** [comment]
I think it needs to be dockerized separately because it's run as a separate server in production, but @jbuck maybe you can confirm?

**Comment by jbuck** [comment]
It needs to be dockerized separately yeah
