### ISSUE TITLE
Add db support for adding a recovery email

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-db-mysql#210]
This issue tracks updates needed to the auth-db-mysql server to support a user adding a recovery email.

Table: 
* Email
  * normalizedEmail:  (String) (Primary Key)
  * email: (String) 
  * uid: (Binary)
  * emailCode: (Binary)
  * isVerified: (Boolean)
  * isPrimary: (Boolean)
  * createdAt (Date)
  * verifiedAt (Date)

Ref: https://docs.google.com/document/d/1DOUWRbxU8ah6AL3gUTrlYKFY42jt_czOHbu4wL4E-sc/edit#, connects with https://github.com/mozilla/fxa-features/issues/27

- [x] Add DB methods, `createEmail`, `getEmails` and `deleteEmail`
- [x] Add `mem` and `mysql` support
- [x] Update tests
- [x] Update docs

**Comment by vladikoff** [comment]
```
uid: (Hex), emailCode: (Hex)
```
 are `binary` not `hex` (other types do not match mysql types, but seems like the uid and emailcode are the more inconsistent looking ones.)
