### ISSUE TITLE
Use "eslint-plugin-fxa" in this repository

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-db-mysql#216]
We need to pick up the latest changes (Buffer fixes, spacing, etc)

Example: https://github.com/mozilla/fxa-content-server/blob/master/package.json#L90

**Comment by morrme** [comment]
https://github.com/mozilla/fxa-auth-db-mysql/blob/master/package.json#L44

currently reads: ` "eslint-config-fxa": "2.1.0",`

Is this what you want to be changed to match the line you linked to above?

**Comment by vladikoff** [comment]
The line needs to be replaced with the other dependency

**Comment by morrme** [comment]
@vladikoff  which would be

`
    "eslint-plugin-fxa": "git://github.com/mozilla/eslint-plugin-fxa.git#84d614b1e137cd9f2441cf56118dafa2c8454124"`    as in the other file?

**Comment by morrme** [comment]
@vladikoff I was only asking to make sure it was that text vs a version number, sorry for the redundant questions! :)

**Comment by vladikoff** [comment]
Hello @morrme! we need to replace the current eslint plugin with the latest GIT SHA of "eslint-plugin-fxa" and make the required code changes to support those eslint rules 👍

**Comment by morrme** [comment]
@vladikoff OK so I was able to get the SHA, so I can make that change, but from there I would need a little mentoring. Would tests reveal the changes that need to be made?

**Comment by vladikoff** [comment]
> Would tests reveal the changes that need to be made?

Yeap they should, once you `npm install` that new dependency and run `node_modules/.bin/grunt eslint` it should do it

**Comment by morrme** [comment]
@vladikoff I got the same output from `grunt eslint` both before and after installing the plugin:

![grunt output](https://cloud.githubusercontent.com/assets/26514778/24678904/08140602-1952-11e7-9704-c4f6ec0e9573.PNG)

No other log or output file was generated.

**Comment by vladikoff** [comment]
@morrme ok! Feel free to sand the change as a patch 👍 and we can take a look at it

**Comment by morrme** [comment]
@vladikoff done! let me know if you detect changes that should be made. I will happily do them! :)
