### ISSUE TITLE
Cleanup old stored procedures?

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-db-mysql#22]
As seen in the following (infra private, sorry!) bug:

  https://bugzilla.mozilla.org/show_bug.cgi?id=1138660#c2

We are creating new stored procedures with each db migration, but we don't ever clean up the old ones.  We now have procedures `forgotPasswordVerified_1`, `forgotPasswordVerified_2` and `forgotPasswordVerified_3` in the db.

We should come up with a scheme for cleaning up old versions once we're confident they'll no longer be needed.

**Comment by chilts** [comment]
Yes. Essentially we can clean up the old ones replaced in the previous release. We shouldn't remove the old ones in the same release - obvious, but just writing it down.

e.g.

* train-1001 - adds createFizzBuzz_27()
* train-1002 - removes createFizzBuzz_26()

**Comment by chilts** [comment]
These look like the old ones to me. This list includes any SPs that were added prior to and including ones train-32 (patch level 8) superseded. I'm just noting these here without a PR yet since that'll have to wait until the next train(-33) is out just in case. Also, I don't wanna mess up #20:

```sql
-- drop old stored procedures
DROP PROCEDURE `createAccountResetToken_1`;
DROP PROCEDURE `createPasswordForgotToken_1`;
DROP PROCEDURE `createPasswordChangeToken_1`;
DROP PROCEDURE `emailRecord_1`;
DROP PROCEDURE `account_1`;
DROP PROCEDURE `forgotPasswordVerified_1`;
DROP PROCEDURE `forgotPasswordVerified_2`;
DROP PROCEDURE `deleteAccount_1`;
DROP PROCEDURE `deleteAccount_2`;
DROP PROCEDURE `resetAccount_1`;
DROP PROCEDURE `resetAccount_2`;
```

**Comment by chilts** [comment]
Included in the PR are 4 more than above:

```sql
DROP PROCEDURE `createAccount_1`;
DROP PROCEDURE `account_1`;
DROP PROCEDURE `emailRecord_1`;
DROP PROCEDURE `verifyEmail_1`;
DROP PROCEDURE `forgotPasswordVerified_1`;
DROP PROCEDURE `forgotPasswordVerified_2`;
DROP PROCEDURE `createAccountResetToken_1`;
DROP PROCEDURE `createPasswordChangeToken_1`;
DROP PROCEDURE `createPasswordForgotToken_1`;
DROP PROCEDURE `resetAccount_1`;
DROP PROCEDURE `resetAccount_2`;
DROP PROCEDURE `resetAccount_3`;
DROP PROCEDURE `deleteAccount_1`;
DROP PROCEDURE `deleteAccount_2`;
DROP PROCEDURE `deleteAccount_3`;
```

It includes 4 of the 6 added for notification stuff (two were new).

**Comment by chilts** [comment]
Rebased onto master so there's no conflict in patch numbers. This patch now contains the following three SPs too:

```sql
DROP PROCEDURE `forgotPasswordVerified_3`;
DROP PROCEDURE `lockAccount_1`;
DROP PROCEDURE `unlockAccount_1`;
```

**Comment by chilts** [comment]
Probably needs updating now.
