### ISSUE TITLE
intermittent >5 second response time on latest

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-db-mysql#221]
These have been flushed from latest's logs, but I have these from IRC yesterday:

>  {"Timestamp":1491853685886000000,"Logger":"fxa-auth-db-server","Type":"bin.server.summary","Severity":6,"Pid":6462,"EnvVersion":"2.0","Fields":{"code":200,"route":"getaccountid","method":"GET","path":"/account/xxxx","t":5654}}

> {"Timestamp":1491922869145000000,"Logger":"fxa-auth-db-server","Type":"bin.server.summary","Severity":6,"Pid":6462,"EnvVersion":"2.0","Fields":{"code":200,"route":"getemailrecordid","method":"GET","path":"/emailRecord/626c6f636b6564302e3935333032303039353132363730333440726573746d61696c2e6e6574","t":7199}}

Ref https://github.com/mozilla/fxa-auth-server/issues/1810
Ref https://github.com/mozilla/fxa-content-server/issues/4922

**Comment by shane-tomlinson** [comment]
cc @jrgm - any ideas? Does the RDS size on latest need to be bumped up?

**Comment by shane-tomlinson** [comment]
If you ssh into latest, /var/log/fxa-auth-db.log-with-slow-queries has a bunch of examples, search for `"t":\d\d\d\d`

**Comment by shane-tomlinson** [comment]
This also kept happening on latest until I restarted the fxa-auth-db-server:

> {"Timestamp":1492097301862000000,"Logger":"fxa-auth-server","Type":"request.summary","Severity":2,"Pid":31001,"EnvVersion":"2.0","Fields":{"op":"request.summary","code":500,"errno":999,"rid":"1492097301854:ip-172-31-6-64:31001:j1gi66im:10159","path":"/auth/v1/account/create","lang":"en","agent":"node-XMLHttpRequest","remoteAddressChain":"[\"95.85.19.180\",\"172.31.11.74\",\"127.0.0.1\"]","t":8,"uid":"00","email":"signin0.07894156780093908@restmail.net","stack":"Error: POOL_ENQUEUELIMIT\n    at handleResponse (/data/fxa-auth-server/lib/pool.js:60:19)\n    at RequestSet.<anonymous> (/data/fxa-auth-server/node_modules/poolee/lib/pool.js:151:4)\n    at RequestSet.handleResponse (/data/fxa-auth-server/node_modules/poolee/lib/request_set.js:66:8)\n    at Endpoint.complete (/data/fxa-auth-server/node_modules/poolee/lib/endpoint.js:162:11)\n    at Endpoint.succeeded (/data/fxa-auth-server/node_modules/poolee/lib/endpoint.js:168:8)\n    at IncomingMessage.gotEnd (/data/fxa-auth-server/node_modules/poolee/lib/endpoint.js:326:8)\n    at emitNone (events.js:72:20)\n    at IncomingMessage.emit (events.js:166:7)\n    at endReadableNT (_stream_readable.js:923:12)\n    at nextTickCallbackWith2Args (node.js:458:9)\n    at process._tickCallback (node.js:372:17)"}}

**Comment by vladikoff** [comment]
@jrgm is there anything in AWS consoles that can show us the MySQL performance? (request latency, etc)?

**Comment by rfk** [comment]
> Does the RDS size on latest need to be bumped up?

From mtg: seems unlikely to help, the db should be plenty big enough for the amount of work it's doing

**Comment by rfk** [comment]
From mtg: we should also try to confirm whether these are caused by AWS CPU usage limits, or perhaps nodejs event-loop blocking, or something else?

**Comment by rfk** [comment]
From mtg: idea: enable newrelic monitoring on latest and see what it shows us

**Comment by jrgm** [comment]
On latest.dev.lcip.org, there is a minutely cronjob that write HH:MM files into /var/tmp/proclist (for show full processlist and /var/tmp/innolist for show engine innodb status), which may have interesting correlating information (if it's a db issue).

**Comment by vladikoff** [comment]
Let's reopen when if this comes back with dockerized latest
