### ISSUE TITLE
Update device name column to utf8mb4

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-db-mysql#229]
This is necessary in order to prevent a variety of non-latin characters from being converted into question marks, and to allow us to store emojis.  We'll need to:

* Add logic in the code to ensure the right encoding is used uniformly
* Make a db migration to fix up the encoding in the production db
* Test it extensively

This will be a nice trial run for fixing up the encoding of the larger, scarier-to-modify "email" column on the accounts table.

**Comment by rfk** [comment]
Once this is done, as a second step we can enable emoji via https://github.com/mozilla/fxa-auth-server/issues/1285

**Comment by rfk** [comment]
Links to https://bugzilla.mozilla.org/show_bug.cgi?id=1348298 which we'll need to check back on once the fix is rolled out.

**Comment by vladikoff** [comment]
from mtg: need to discuss this

**Comment by vladikoff** [comment]
https://mathiasbynens.be/notes/mysql-utf8mb4 

Stored procedures comment: https://mathiasbynens.be/notes/mysql-utf8mb4#comment-61

**Comment by vladikoff** [comment]
I tried to use emojis with the **changed** the character set with display name in fxa_profile.profile:

```
Executing:
UPDATE `fxa_profile`.`profile` SET `displayName`='hello hello 💥' WHERE `userId`=0x3EBF1EBB62BE4AB4A84516560E5E45AE;

Operation failed: There was an error while applying the SQL script to the database.
ERROR 1366: 1366: Incorrect string value: '\xF0\x9F\x92\xA5' for column 'displayName' at row 1
SQL Statement:
UPDATE `fxa_profile`.`profile` SET `displayName`='hello hello 💥' WHERE `userId`=0x3EBF1EBB62BE4AB4A84516560E5E45AE
```

**Comment by rfk** [comment]
the todo list:
* export current db schema for testing out locally
* change the charset and collation on the column
    * need to pick a correct collation, including case-sensitivity
    * max size of 191 because of index size limitations
* update the stored procedures that touch it
* ensure all connections use the right encoding (similar to how we're enforcing strict mode)
* update Joi validation rules to allow the additional characters

**Comment by rfk** [comment]
@vladikoff @jbuck did we learn any lessons from updating the profile display-name column to utf8mb4, that we should take into consideration here?

**Comment by vladikoff** [comment]
for train-93

**Comment by vladikoff** [comment]
fro mtg: 

* seems like the profile server migration rewrote the column in MySQL

Updated TODO list:

- [ ] export current db schema for testing out locally
- [ ] change the charset and collation on the column
  - [ ] need to pick a correct collation, including case-sensitivity
  - [ ] max size of 191 because of index size limitations
- [ ] update the stored procedures that touch it
- [ ] ensure all connections use the right encoding (similar to how we're enforcing strict mode)
- [ ] update Joi validation rules to allow the additional characters

**Comment by rfk** [comment]
The migration for this stuck in production, thanks to gh-ost!  IIUC, the next steps here are to:

* Copy across existing values from the "name" column into the "nameUtf8" column, for cases where "nameUtf8" is NULL.
* Update the stored procedures to read "nameUtf8" rather than "name", or perhaps to use `COALESCE(nameUtf8, name)` if we want to do it concurrently with the big copy above.

Is there anything else to do in order to close this out?

**Comment by vladikoff** [comment]
> Copy across existing values from the "name" column into the "nameUtf8" column, for cases where "nameUtf8" is NULL.

from mtg: @jbuck @jrgm on that

> Update the stored procedures to read "nameUtf8" rather than "name", or perhaps to use COALESCE(nameUtf8, name) if we want to do it concurrently with the big copy above.

from mtg: @vladikoff on this, to update stored procedures.
