### ISSUE TITLE
Migrate to using primary email on email table

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-db-mysql#244]
This is a tracking issue to support the migration. Per https://github.com/mozilla/fxa-auth-db-mysql/pull/243#issuecomment-306383709

- [x] Update stored procedures to ensure primary email on account and emails table are in sync. https://github.com/mozilla/fxa-auth-db-mysql/pull/241
- [x] Migration script to add all existing account emails to emails table. https://github.com/mozilla/fxa-auth-db-mysql/pull/247
- [x] Update stored procedures to use emails table. https://github.com/mozilla/fxa-auth-db-mysql/pull/245

**Comment by vbudhram** [comment]
All issues for this have been merged, will close once #245 is deployed in next train.

**Comment by vladikoff** [comment]
@vbudhram to check if this can be closed

**Comment by vbudhram** [comment]
Train 90 is in production, https://philbooth.me/fxa, closing!
