### ISSUE TITLE
Should we remove the updateSessionToken endpoint/method/stored procedure?

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-db-mysql#255]
Now that session tokens are updated in redis, should we drop all of the `updateSessionToken` related stuff from this repo?

**Comment by vladikoff** [comment]
yeap!

**Comment by deeptibaghel** [comment]
@vladikoff can i take this up ?

**Comment by philbooth** [comment]
Sorry @deeptibaghel, since this issue got opened we started using `updateSessionToken` again in mozilla/fxa-auth-server#2302 and forgot to close this. Closing it now.
