### ISSUE TITLE
Don't run eslint in npm test

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-db-mysql#257]
This repo runs eslint when you do `npm t`. That's really annoying if you're trying to debug why some tests are failing locally and you insert a bunch of `console.log` to debug. Now the tests don't even run because the linter helpfully reports `Unexpected console statement` then craps out.

We can still incorporate the linter as part of `npm run test-travis` for CI.

**Comment by shane-tomlinson** [comment]
> We can still incorporate the linter as part of npm run test-travis for CI.

It can also be done as a pre-push git hook get quicker feedback. The content server does it that way and it's saved me quite a few times.

**Comment by philbooth** [comment]
> It can also be done as a pre-push git hook to get quicker feedback. The content server does it that way and it's saved me quite a few times.

That annoys me too tbh. I should be able to push a WIP branch without eslint getting all uppity about it and making me use `--no-verify`. I push more WIP branches than I do non-WIP branches, so the default behaviour should stay out of my way. I'm very happy to run eslint manually when I want it to run locally.

**Comment by philbooth** [comment]
Essentially, I don't want to work in a Nanny State. Let me ride my bike without stabilizers until it is time to open a pull request.
