### ISSUE TITLE
Discussion on mysql-patcher and production

### ISSUE THREAD

**Issue by chilts** [mozilla/fxa-auth-db-mysql#26]
Just trying to capture a few options for the patcher and production to see if we can somehow automate this in a particular way but being safe about it as well.

### Current Solution Problems ###

* the patching is done manually in prod, an issues needs to be raised for the patch to be applied
* the patch needs manual adjusting if it contains stored procedures, this could add introduce an error when being created
* patching (if using the mysql-patcher) is somewhat opaque due to the entire SQL file being sent to MySql in one go, i.e. it worked or it failed and there isn't any statement level insight or logging

### Solution 1: Run `mysql-patcher` in Prod ###

The current `mysql-patcher` sends the entire patch file to mysql in one go, for it to execute every statement. Without some overseeing, some MySql statements (such as adding a column or an index) may not complete correctly. Since MySql doesn't have transactional DDL, this may have failed in the middle of a patch file and therefore would need manual inspection to check which statements have or haven't been applied correctly. Whether the patch level in `dbMetadata` is or isn't updated correctly the database then differs from any patch.

### Solution 2 : Change `mysql-patcher` to run each individual statement in each patch file ###

This may work. It introduces some overhead to delimit the statements in the patch files so that the `mysql-patcher` can send each statement to MySql separately. The patcher program could then keep re-trying (up to a certain limit) to make sure each statement is executed in turn. If any statement fails up to a maximum of times, it could then try to reverse the patch number. The ability to log more info related to which statement is being applied, the length of time it took and what failed would make this process more transparent. This would still require at least manual oversight to make sure nothing is going awry.

### Solution 3 : Perform all patching in code, not SQL ###

By having each statement in code means we wouldn't need to instrument any patch files with delimiters since they would already be separate. Again, each statement could be performed in turn with some retry logic and perhaps a patch reversal process if anything in the patch fails too many times. Again, manual oversight would also be required though the extra logging information would also help make sure it went smoothly.

@jrgm: Do either of the last two solutions appeal to you, or anything else? Have you got any other suggestions? /cc @rfk @ckolos. Thanks.

**Comment by ckolos** [comment]
Personally, I don't care for running the updates as part of script or a non-interactive, step by step process. I'd rather get a list of 10 separate steps, each one evaluated independently for success, than run the risk of having one step fail completely/subtly.

**Comment by chilts** [comment]
In which case, I don't think we need to change anything. @jrgm ... you may have other opinions. :)

**Comment by chilts** [comment]
Am leaning towards closing this. @jrgm are you happy (enough) with the status-quo?

**Comment by rfk** [comment]
Thanks for digging into the options here @chilts, but sounds like the status-quo is the favoured approach for now.  Let's close this out.
