### ISSUE TITLE
Add STRICT_ALL_TABLES and NO_ENGINE_SUBSTITUTION  required sql mode support 

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-db-mysql#277]
Example: https://github.com/mozilla/fxa-profile-server/blob/3e3879a6abbe628b41268d3a82d1ed744e037113/lib/db/mysql/index.js#L17

**Comment by hritvi** [comment]
Hey @vladikoff! Can I work on this?

**Comment by vladikoff** [comment]
> Hey @vladikoff! Can I work on this?

This bug is more complex than other ones, you can give it a try, but I suggest something with a `help wanted` label

**Comment by deeptibaghel** [comment]
@vladikoff  can i get a brief on what all should i understand  to be able to start working on this issue.

**Comment by vladikoff** [comment]
@deeptibaghel when connection to MySQL gets initialized from the server it runs some queries to make sure the future queries will run correctly. We already have one we wrote here: https://github.com/mozilla/fxa-auth-db-mysql/blob/cc6e08b7d6aba6b15d06f34ee5efe0c15bc1d72b/lib/db/mysql.js#L1054

Besides `SET NAMES` we also need to `SET SESSION sql_mode` joined from an array of modes. This is already done in the profile server : https://github.com/mozilla/fxa-profile-server/blob/3e3879a6abbe628b41268d3a82d1ed744e037113/lib/db/mysql/index.js#L259

**Comment by vladikoff** [comment]
@deeptibaghel there is also a test for that here: https://github.com/mozilla/fxa-profile-server/blob/90da3fae5737d4263faa9d902399831a7f273e4c/test/mysql.js#L44 

We need to do the same here. Let's add the same 2 modes here as well:
```js
const REQUIRED_SQL_MODES = [
  'STRICT_ALL_TABLES',
  'NO_ENGINE_SUBSTITUTION',
];
```

**Comment by deeptibaghel** [comment]
Thanks @vladikoff
