### ISSUE TITLE
Token pruning appears to be causing lock contention in the db

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-db-mysql#294]
We recently started getting some spurts of `500` errors on the auth-server, due to `ER_LOCK_WAIT_TIMEOUT` errors coming back from auth-db-mysql.  After poking around in the query state in MySQL, @jrgm identified the session-token-pruning query as having been stuck running for many hours, holding locks on three tables and blocking other queries from proceeding:

```
    DELETE st, ut
    FROM sessionTokens AS st
    LEFT JOIN unverifiedTokens AS ut
    ON st.tokenId = ut.tokenId
    WHERE st.createdAt > @pruneFrom
    AND st.createdAt <= @pruneUntil
    AND NOT EXISTS (
      SELECT sessionTokenId FROM devices
      WHERE uid = st.uid AND sessionTokenId = st.tokenId
    );
```

He killed the query and db performance appears to have recovered, although we'll continue to monitor over the next few days.

We haven't shipped any changes to the pruning code recently so I'm surprised to see this query getting stuck and it's not clear how to proceed.  I'll try to brainstorm a few ideas for ways to debug, and @mozilla/fxa-devs all suggestions are welcome!

**Comment by rfk** [comment]
So, first step I guess would be to do an sanity-checking `EXPLAIN` on this statement to check whether it's using all the appropriate indexes that it should be using.

It would also be useful to know what sort of date range it's trying to prune here.  Can we try the following to get a sense of what's being attempted, maybe on the replica?

* Find where it's trying to prune from: `SELECT pruneFrom FROM dbMetadata WHERE name = 'sessionTokensPrunedUntil'` to find the starting point
* Find where it's trying to prune until: `SELECT MAX(createdAt) AS pruneUntil FROM (
      SELECT createdAt FROM sessionTokens
      WHERE createdAt >= @pruneFrom
      AND NOT EXISTS (
        SELECT sessionTokenId FROM devices
        WHERE uid = sessionTokens.uid
        AND sessionTokenId = sessionTokens.tokenId
      )
      ORDER BY createdAt
      LIMIT 10000
    )`
* Find how many rows it's trying to prune: `SELECT COUNT(*) FROM sessionTokens AND st.createdAt <= @pruneUntil
    AND NOT EXISTS (
      SELECT sessionTokenId FROM devices
      WHERE uid = st.uid AND sessionTokenId = st.tokenId
    );`

Finally, the pruning task logs some info logs like `log.info('MySql.pruneTokens')` and `log.info('MySql.pruneTokens', { msg: 'Finished' })`.  Can we find these in the auth-db-mysql application logs, and use them to tell whether the token-pruning job has been taking progressively longer and longer to execute?

I'm wondering if we've hit a point in the sessionTokens backlog history, where a higher proportion of tokens now have a device record, and the query is hence scanning a lot more rows before it finds a batch to prune.  If we find that the timestamp in `@pruneFrom` correlates with the time at which we launched some device-registration feature in Firefox, that would lend weight to this theory.

**Comment by rfk** [comment]
> `SELECT pruneFrom FROM dbMetadata WHERE name = 'sessionTokensPrunedUntil'`

@jrgm reports that the value of "sessionTokensPrunedUntil" is....

...drumroll...

The empty string.  Which MySQL will interpret as zero when coerced to an integer.  So the prune query was probably trying to delete from the start of time and having to scan past a vast number of non-expired session tokens before it could find useful work to do.

Not yet sure how we got into such a state, but it seems like a good explanation for the observed behavior.

**Comment by rfk** [comment]
> Not yet sure how we got into such a state, but it seems like a good explanation for the observed behavior.

I have a theory.

The code that updates the value of "sessionTokensPrunedUntil" is:

```
  UPDATE dbMetadata
  SET value = @pruneUntil
  WHERE name = 'sessionTokensPrunedUntil';
```

We know the auth-server db to still be running without strict mode, meaning mysql will happily do all sorts of exciting coercions in order to get queries to succeed.  If we attempt to insert a `NULL` into this column, it would get coerced to the empty string like this:

```
mysql> INSERT INTO dbMetadata VALUES ('test-key', 12345);
Query OK, 1 row affected (0.01 sec)

mysql> SELECT * FROM dbMetadata WHERE name = 'test-key';
+----------+-------+
| name     | value |
+----------+-------+
| test-key | 12345 |
+----------+-------+
1 row in set (0.00 sec)

mysql> UPDATE dbMetadata SET value = NULL WHERE name = 'test-key';
Query OK, 1 row affected, 1 warning (0.01 sec)
Rows matched: 1  Changed: 1  Warnings: 1

mysql> SELECT * FROM dbMetadata WHERE name = 'test-key';
+----------+-------+
| name     | value |
+----------+-------+
| test-key |       |
+----------+-------+
1 row in set (0.00 sec)
```

Could the value of `@pruneUntil` ever be `NULL`?
The query that calculates it looks like this:

```
    SELECT @pruneUntil := MAX(createdAt) FROM (
      SELECT createdAt FROM sessionTokens
      WHERE createdAt >= @pruneFrom AND createdAt < olderThan
      AND NOT EXISTS (
        SELECT sessionTokenId FROM devices
        WHERE uid = sessionTokens.uid
        AND sessionTokenId = sessionTokens.tokenId
      )
      ORDER BY createdAt
      LIMIT 10000
    ) AS prunees;
```

If we get to the point where we have no expired session tokens, then the inner `SELECT` here will return zero rows, and the resulting `MAX` will be `NULL`.

So my current theory is:

* the pruning job finally caught up on its backlog of expired tokens
* which caused subsequent pruning runs to calculate `@pruneUntil = NULL`
* which caused them to record `sessionTokensPrunedUntil=NULL` at the end of the run
* which MySQL coerced into `""` on its way into the database
* which caused subsequent pruning runs to start using `@pruneFrom = ""`
* which MySQL coerced into integer zero when evaluating `WHERE createdAt > @pruneFrom`
* which was fine until enough time passed for more tokens to expire
* at which point pruning runs would once again calculate a non-`NULL` value for `@pruneUntil`
* and hence would try to examine every token between `@pruneUntil` and the beginning of time

There will be millions of tokens between `@pruneUntil` and the beginning of time, all of which can't be purged because they have a device record attached.  But the purge job would examine every single one of them in order to establish this fact.

**Comment by jrgm** [comment]
To answer some previous questions: the one about 'SELECT MAX(createdAt)' is NULL.
The one about 'SELECT COUNT(*)' has a couple of syntax errors, but, if I interpret what you meant correctly, the value is 0. But that may not be surprising given what's in further comments. 

However, I can't quite reconcile some operations data points. In hindsight, things changed when train-103 was **built** (which means new background tasks being live).

**Comment by rfk** [comment]
> In hindsight, things changed when train-103 was built (which means new background tasks being live).

I wonder if the prune job on train-102 had died or otherwise got stuck, and building train-103 caused a new pruning job to spin up in the background and trigger the symptoms seen here.
