### ISSUE TITLE
Delete sessionToken and sessionTokenWithVerificationStatus

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-db-mysql#306]
When mozilla/fxa-auth-server@4941dd5b landed (train 92), the auth server stopped hitting the `sessionToken` and `sessionTokenWithVerificationStatus` db endpoints. We should delete them, and their associated methods, stored procedures, documentation et cetera and so on.

**Comment by vladikoff** [comment]
Yay!
