### ISSUE TITLE
Let's auto-generate the reverse migrations

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-db-mysql#307]
This is super low-priority because we never actually run them anyway, but that's also the reason why little errors occasionally creep in that we don't notice. It's too easy to get e.g. a stored procedure version number wrong.

Given that their relationship is entirely deterministic, it seems eminently doable to write a script that generates a reverse migration based on whatever is in the equivalent forward migration. That would save us hassle and prevent us making mistakes.

**Comment by ArkadiyVoronov** [comment]
I can work on that.

**Comment by vladikoff** [comment]
@ArkadiyVoronov 👍

**Comment by vladikoff** [comment]
getting rid of reverse migrations, so we don't need this anymore
