### ISSUE TITLE
Convert remaining '= Buffer(stuff)' to 'Buffer.from(stuff,...)'

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-db-mysql#316]
Here are some: 

![image](https://user-images.githubusercontent.com/128755/37220954-3f728da4-2396-11e8-8cab-7e7add77d32a.png)

**Comment by vladikoff** [comment]
cc @deeptibaghel

**Comment by deeptibaghel** [comment]
I will do it @vladikoff :)

**Comment by vladikoff** [comment]
@deeptibaghel  thank you! This should be easier than the other one, there are more occurrences of this in the auth server  https://github.com/mozilla/fxa-auth-server/issues/2333
