### ISSUE TITLE
Remove `createdAt` column on recoveryCode table

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-db-mysql#340]
These values are never returned to the user and not used internally, so I propose we remove 🗡 the column. Additionally, they are not storing a unix timestamp value.

**Comment by vladikoff** [comment]
@deeptibaghel hey, do you want to try fix this issue? We have a script that makes migrations a bit easier: https://github.com/mozilla/fxa-auth-db-mysql/blob/master/scripts/migration.sh

**Comment by deeptibaghel** [comment]
@vladikoff happy to work this :)

**Comment by vladikoff** [comment]
@deeptibaghel let us know if you have questions! 👍
