### ISSUE TITLE
mysql-patcher missing in fxa-dev

### ISSUE THREAD

**Issue by vladikoff** [mozilla/fxa-auth-db-mysql#343]
Ref: https://github.com/mozilla/identity-pubkeys/pull/24#issuecomment-383782280

cc @jrgm 

I downgraded to v110 and it's fine now. so it's something to do with npm / node changes

**Comment by jrgm** [comment]
I think this is fixed now, ya? In https://github.com/mozilla/fxa-auth-db-mysql/pull/344

**Comment by vladikoff** [comment]
Should be !
