### ISSUE TITLE
Add recovery key database support

### ISSUE THREAD

**Issue by vbudhram** [mozilla/fxa-auth-db-mysql#346]
This issue tracks items needed to add the ability to create/consume recovery keys.

### New Tables

Recovery Key Table

| Column        | Description           | Options  | Datatype|
| ------------- | ------------- | ----- | ------ |
| uid      | account's uid      |   NOT NULL | BINARY(16)|
| recoveryKeyId| recovery key id     |    NOT NULL | BINARY(32)|
| recoveryData| unbundle containing wrapKb+recovery key     |    NOT NULL | TEXT|

#### .createRecoveryKey(uid, recoverykId, recoveryData)

Creates a new recovery key for an account.

Parameters:

* uid - (Buffer16) the uid of the account
* recoverykId - (binary)
* recoveryData - (binary)

Returns:

* resolves with:
    * {}
* rejects: with one of:
    * any error from the underlying storage engine

#### .deleteRecoveryKey(uid, recoverykId)

Consumes the recovery key

Parameters:

* uid - (Buffer16) the uid of the account
* recoverykId - (Buffer32)

Returns:

* resolves with:
    * an object `{}`
    * recoveryData
* rejects: with one of:
    * `error.notFound()`
    * any error from the underlying storage engine

#### .getRecoveryKey(uid, recoverykId)

Get the recovery key

Parameters:

* uid - (Buffer16) the uid of the account
* recoverykId - (Buffer32)

Returns:

* resolves with:
    * an object `{}`
    * recoveryData
* rejects: with one of:
    * `error.notFound()`
    * any error from the underlying storage engine

#### Delete recovery key

* Method : `DELETE`
* Path : `/account/<uid>/recoveryKey/<kId>`
  * `uid` : string
  * `kId`: string

#### Create recovery key

* Method : `POST`
* Path : `/account/<uid>/recoveryKey`
  * `uid` : hex128
  * `recoverykId` : string
  * `recoveryData`: binary

#### Get recovery key

* Method : `GET`
* Path : `/account/<uid>/recoveryKey/<kId>`
  * `uid` : hex128
  * `recoverykId` : string

child of mozilla/fxa#297

**Comment by rfk** [comment]
> Recovery Key Table

Noting that the primary key for this table should be over (uid, recoverykId).

I also wonder if we can find a name for "recoverykId" that's a little less awkward to write and to capitalize, e.g. "recoveryKeyId".

> .createRecoveryKey(uid, recoverykId, recoveryData)

Does this allow creation of multiple recovery keys?

> .consumeRecoveryKey(uid, recoverykId)

"Consume" implies that the recovery key will be removed by this method, but it's exposed as a `GET` request which implies that it is side-effect free.  Do we intend to delete the key as part of "consumeRecoveryKey", or as part of a subsequent account reset?
