### ISSUE TITLE
Pull sessionToken out of the devices table

### ISSUE THREAD

**Issue by eoger** [mozilla/fxa-auth-db-mysql#378]
In the OAuth world, devices will not only be associated with a session token anymore.
This is why we should pull the `sessionTokenId` column out of the `devices` table and create a 1:1 `deviceId`: `sessionTokenId` table.
Since it's a big migration, we should probably do it in multiple steps just like we did with the `utf8mb4` display names:
1. Create the `devicesSessionTokens` table. Modify the queries to double write `sessionTokenId` both in the `devices` table and in this new table.
2. Run a procedure to create the remaining `devicesSessionTokens` rows for devices which haven't been updated since step 1.
3. Update the read/write queries to only use `devicesSessionTokens`.
4. Remove the `sessionTokenId` column from `devices`.

@rfk does that sound like a good plan to you?

**Comment by vladikoff** [comment]
from mtg:

devicesToSessionToken table
devicesToRefreshToken table

**Comment by eoger** [comment]
I like your idea @philbooth, this would ease the migration pain, and at the same time allow us to evolve the oauth side of things without breaking compatibility with the old sessionToken devices world. What do other people think?

**Comment by philbooth** [comment]
@eoger, I've made a note to bring this up in the back-end meeting later, to see if @jrgm has a preference one way or the other.

**Comment by vladikoff** [comment]
Not doing this for now...
