### ISSUE TITLE
Remove use of ROW_COUNT() and forbid its return

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-db-mysql#411]
In [Bug 1499819](https://bugzilla.mozilla.org/show_bug.cgi?id=1499819) we identified use of the `ROW_COUNT()` function as causing significant db replication lag in production.  In #410 we modified two of our more frequently-called stored procedures to remove it, and that seems to have fixed the db lag issue.

For completeness, we should:

* Remove use of `ROW_COUNT()` from other stored procedures, even if they're only called occasionally.
* Update out mysql linting/CI logic to detect future attempts to use `ROW_COUNT()`, and forbid them.

**Comment by shane-tomlinson** [comment]
From meeting - 2 of the calls have been removed, 4 more remain.

**Comment by shane-tomlinson** [comment]
@jrgm mentions there are a number of things you can do with MySQL and replication that are non-deterministic and should be addressed.

**Comment by philbooth** [comment]
Taking my face off this because I've opened a PR (#419) for the second bullet point, but haven't done anything to address the first one.
