### ISSUE TITLE
Add lint checks for explicit email string encoding

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-db-mysql#440]
As we discovered in https://bugzilla.mozilla.org/show_bug.cgi?id=1504907#c5, there's a bad interaction between stored procedures and the utf-vs-utf8mb4 character encoding in MySQL.  If we create a stored procedure that takes an email address and uses it in a subquery like this:

```
CREATE PROCEDURE `get_uid_for_email` (
   IN `inEmail` VARCHAR(255)
)
BEGIN
 EXPLAIN SELECT
     a.uid
 FROM
     accounts a,
     emails e
 WHERE
     a.uid = (SELECT uid FROM emails WHERE normalizedEmail = LOWER(inEmail))
 AND
     a.uid = e.uid
 END
```

Then MySQL will fail to use the correct index due to an ecoding issue.  The `inEmail` parameter is `utf8mb4` because we enforce that encoding on all new connections.  The `normalizedEmail` column is the three-byte `utf8` encoding.  For whatever reason MySQL decides it can't satisfy `WHERE normalizedEmail = LOWER(inEmail))` using the `utf8` index on that column and falls back to a full table scan.

The right fix long-term is to get the `normalizedEmail` column upgraded to `utf8mb4` encoding, but that's a long process.

Short-term, we could guard against future instances of this error by linting our SQL to ensure that any "email" parameter has an explicit utf8 encoding declared.  So it would reject something like:

```
   IN `inEmail` VARCHAR(255)
```

But would accept something like:

```
   IN `inEmail` VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin
```

Because we know all of our email-related columns are currently `utf8` only.

What do you think, is it worth adding a lint to preserve organizational memory of this issue, in case getting the column upgraded takes a long time?

**Comment by philbooth** [comment]
> What do you think, is it worth adding a lint to preserve organizational memory of this issue, in case getting the column upgraded takes a long time?

SGTM
