### ISSUE TITLE
Implement "client instances" and deprecate "devices"

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-db-mysql#444]
Over in https://github.com/mozilla/fxa-auth-server/issues/2547 and [1] we've been working through what our currently-very-sync-specific "devices API" should look like in an OAuth world, and we've come up with a more general notion of a "client instance" to replace our current notion of a "device".  If it's a good notion, we should be able to deprecate the current device-related DB APIs and replace them with a more general "client instances api".  So let's try it!

@eoger put together an initial version of this in https://github.com/mozilla/fxa-auth-db-mysql/pull/436/; thanks @eoger!

In that version, "client instances" and "devices" live side-by-side two parallel incarnations of a similar underlying idea.  I think with a bit of tweaking we could make the client-instances stuff a superset of the devices stuff, and look towards deprecating the former.

Conceptually, a "client instance" is a metadata record about a particular instance of some client software that's connected to the user's account.  It has a unique opaque identifier and a `client_id` that identifies the type of client software (Firefox Desktop, Lockbox for Android, etc).  It has a `sessionToken` **and/or** a `refreshToken` representing its connection to the user's account.  It has some automatically-tracked metadata like OS and platform, and some client-provided metadata like display name, push endpoint and so-on.  And it can use our infrastructure to interact with other client instances by sending/receiving notifications and commands.

That's basically our current "device" data model, except it's allowed to have a `refreshToken` instead of (or in addition to [2]) a `sessionToken`, and it has an explicit `client_id`.

The current device-related APIs are:
* list all devices : `GET /account/:id/devices`
* find device for a given sessionToken verification id: `GET /account/:id/tokens/:tokenVerificationId/device`
* create a new device record: `PUT /account/:id/device/:deviceId`
* update a existing device record: `POST /account/:id/device/:deviceId/update`
* delete a device record : `DELETE /account/:id/device/:deviceId`

We can deprecate these in favour of more general client-instance equivalents:
* list all client instances: `GET /account/:uid/client_instances`
* find client instance for a given sessionToken verification id: `GET /account/:uid/tokens/:tokenVerificationId/client_instance`
* read client instance metadata: `GET /account/:uid/client_instance/:id`
* upsert client instance metadata: `POST /account/:uid/client_instance/:id`
* delete a client instance: `DELETE /account/:uid/client_instance/:id`

Making new APIs gives us a chance to clean up terminology, rename fields for consistency with how they're used in the auth-server, and simplify calling code by offering "upsert".  And I think it will help us shake out the conceptual details of the broader proposal in https://github.com/mozilla/fxa-auth-server/issues/2547.

[1] https://docs.google.com/document/d/1pbyOOySw76R-OTPJiX4gW3Izlp-plA7T7Jlt-wOAKwQ/edit
[2] Why "in addition to"? I expect we'll want this in order to deal with cases like Fenix where you have a sessionToken from logging in via web content, and a refreshToken for use by the client software itself, but they both "belong to" to same piece of client software.

**Comment by rfk** [comment]
In the DB, we currently have these tables:

```
mysql> describe devices;
+-------------------+---------------------+------+-----+---------+-------+
| Field             | Type                | Null | Key | Default | Extra |
+-------------------+---------------------+------+-----+---------+-------+
| uid               | binary(16)          | NO   | PRI | NULL    |       |
| id                | binary(16)          | NO   | PRI | NULL    |       |
| sessionTokenId    | binary(32)          | YES  |     | NULL    |       |
| name              | varchar(255)        | YES  |     | NULL    |       |
| nameUtf8          | varchar(255)        | YES  |     | NULL    |       |
| type              | varchar(16)         | YES  |     | NULL    |       |
| createdAt         | bigint(20) unsigned | YES  |     | NULL    |       |
| callbackURL       | varchar(255)        | YES  |     | NULL    |       |
| callbackPublicKey | char(88)            | YES  |     | NULL    |       |
| callbackAuthKey   | char(24)            | YES  |     | NULL    |       |
| callbackIsExpired | tinyint(1)          | NO   |     | 0       |       |
+-------------------+---------------------+------+-----+---------+-------+
11 rows in set (0.00 sec)
```

And:

```
mysql> describe sessionTokens;
+--------------------+---------------------+------+-----+---------+-------+
| Field              | Type                | Null | Key | Default | Extra |
+--------------------+---------------------+------+-----+---------+-------+
| tokenId            | binary(32)          | NO   | PRI | NULL    |       |
| tokenData          | binary(32)          | NO   |     | NULL    |       |
| uid                | binary(16)          | NO   | MUL | NULL    |       |
| createdAt          | bigint(20) unsigned | NO   | MUL | NULL    |       |
| uaBrowser          | varchar(255)        | YES  |     | NULL    |       |
| uaBrowserVersion   | varchar(255)        | YES  |     | NULL    |       |
| uaOS               | varchar(255)        | YES  |     | NULL    |       |
| uaOSVersion        | varchar(255)        | YES  |     | NULL    |       |
| uaDeviceType       | varchar(255)        | YES  |     | NULL    |       |
| lastAccessTime     | bigint(20) unsigned | NO   |     | 0       |       |
| uaFormFactor       | varchar(255)        | YES  |     | NULL    |       |
| authAt             | bigint(20) unsigned | YES  |     | NULL    |       |
| verificationMethod | int(11)             | YES  |     | NULL    |       |
| verifiedAt         | bigint(20)          | YES  |     | NULL    |       |
| mustVerify         | tinyint(1)          | YES  |     | 1       |       |
+--------------------+---------------------+------+-----+---------+-------+
15 rows in set (0.00 sec)
```

Ideally, we could just rename the `devices` table to `client_instances` and add a nullable `refreshTokenId` column.  That's not going to be possible on our production system, but I think we can achieve what we want by:

* Adding a new table to track the mapping from client instance ids to refresh tokens
* Joining this table with the existing devices table in our various queries

So reading all client-instances on an account would look something like:

```
CREATE PROCEDURE `clientInstances_1` (
  IN `uidArg` BINARY(16)
)
BEGIN
  SELECT
    inst.uid,
    inst.id,
    inst.sessionTokenId,
    inst_oauth.refreshTokenId,
    inst_oauth.clientId,
    inst.nameUtf8 AS name,
    inst.type,
    inst.createdAt,
    inst.callbackURL AS pushCallback,
    inst.callbackPublicKey AS pushPublicKey,
    inst.callbackAuthKey AS pushAuthKey,
    insti.callbackIsExpired AS pushCallbackExpired,
    s.uaBrowser,
    s.uaBrowserVersion,
    s.uaOS,
    s.uaOSVersion,
    s.uaDeviceType,
    s.uaFormFactor,
    s.lastAccessTime,
    cmds.commandName,
    inst_cmds.commandData
  FROM devices AS inst
  INNER JOIN clientRefreshTokens AS inst_oauth
    ON inst.id = int_oauth.id
  INNER JOIN sessionTokens AS s
    ON inst.sessionTokenId = s.tokenId
  LEFT JOIN (
    deviceCommands AS inst_cmds FORCE INDEX (PRIMARY)
    INNER JOIN deviceCommandIdentifiers AS cmds FORCE INDEX (PRIMARY)
      ON inst_cmds.commandId = cmds.commandId
  ) ON (inst_cmds.uid = inst.uid AND inst_cmds.deviceId = inst.id)
  WHERE inst.uid = uidArg
  ORDER BY 1, 2;
END;
```

That's....well, it's a lot of joining!  But I think we can hide it behind a nice unified API.

If I get a chance while travelling, I'll try to prototype something along these lines on top of https://github.com/mozilla/fxa-auth-db-mysql/pull/436/.

@eoger, please intervene if you already tried to go down a similar route and it didn't work out...

**Comment by vbudhram** [comment]
> find device for a given sessionToken verification id: GET /account/:id/tokens/:tokenVerificationId/device

Sorry for drive by, but this caught my eye and I was a little confused by it. What was the original use case for looking up a session with the `tokenVerificationId` to get device info?  If a session has been verified through some means, a value wouldn't exist in that table. 

Would using the `GET /sessionToken/:id/device` make sense here?

> That's....well, it's a lot of joining! But I think we can hide it behind a nice unified API.

Heh yea it is a lot of joining. Over in https://github.com/mozilla/fxa-auth-db-mysql/blob/4b4f7d490eeabe22315a6a19880ae2defeefd697/lib/db/schema/patch-090-091.sql#L129 we did alot of joins, but I think it has been working out performance wise considering it is one of our most hit procedures.

**Comment by eoger** [comment]
IIUC thus query considers the `devices` table as canonical: I feel strongly about having the refresh tokens being the canonical one instead so we can have "default" metadata for refresh tokens who were not associated with an instance row yet.

**Comment by rfk** [comment]
I haven't succeeded in making significant time for this, but it'll be my top priority for this coming week.  I've pushed my WIP code to a PR here for visibility:

  https://github.com/mozilla/fxa-auth-db-mysql/pull/449

**Comment by vladikoff** [comment]
@rfk it seems like we are not this plan, should we start a new bug with the new plan?

**Comment by rfk** [comment]
Yep, sounds good, new plan == new bug.

**Comment by vladikoff** [comment]
a bunch of this was done, not sure why this is open still but reopen and let us know :)
