### ISSUE TITLE
accountReset and accountDelete should delete from deviceCommands

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-db-mysql#479]
This was an oversight in https://github.com/mozilla/fxa-auth-db-mysql/pull/354.  Rows in the "devices" table can be referenced by rows in the "deviceCommands" table.  We don't have any foreign key constraints, so when we delete from the former (e.g. on account reset or account delete) then we should also delete from the later.

**Comment by jrgm** [comment]
As noted in #485 there are FK constraints on `deviceCapabilities`, `deviceCommands` referencing `devices`, although we'd like to remove those.

**Comment by rfk** [comment]
We'll do this as part of https://github.com/mozilla/fxa-auth-db-mysql/pull/483 when we remove the `ON CASCADE DELETE`.
