### ISSUE TITLE
Use mozlog

### ISSUE THREAD

**Issue by chilts** [mozilla/fxa-auth-db-mysql#5]
mozlogify all the things.

**Comment by AkhilHector** [comment]
@chilts Hey i am interested to contribute to this project ! Can i be of any help ?

**Comment by vladikoff** [comment]
@AkhilHector Hey, this particular bug has to deal with replacing the [bunyan](https://github.com/mozilla/fxa-auth-db-mysql/blob/master/package.json#L22) logger package with https://www.npmjs.com/package/mozlog 

Here is an example of how fxa-oauth-server uses mozlog: https://github.com/mozilla/fxa-oauth-server/search?utf8=%E2%9C%93&q=logger

**Comment by AkhilHector** [comment]
@vladikoff Ohk ! Where else is the mozlog required to be implemented ?

**Comment by chilts** [comment]
@AkhilHector there are a couple of other backend repos which would need to be mozlog(ified) but let's shoot for this one first. Let me know if there's anything else you need.

**Comment by AkhilHector** [comment]
@chilts Thanks for letting me. As of now i am pretty comfortable with the facts and as soon as i get a doubt I'll bug you !

**Comment by AkhilHector** [comment]
@chilts what is the significance of patch ? I'm a bit stuck there

**Comment by AkhilHector** [comment]
@chilts Hey can you do a code review for me, I am struck at a point !

**Comment by chilts** [comment]
Hi @AkhilHector - sure. What would you like me to look at?

Do you mean these commits here? https://github.com/AkhilHector/fxa-auth-db-mysql/commits/master

(Note: you'll have problems in the future if you rebase your master on top of this repo's master, so it's probably best to work in a branch rather than on your master branch.)

**Comment by AkhilHector** [comment]
@chilts oh yes i'll checkout another branch and are you available on irc #fxa ?

**Comment by chilts** [comment]
@AkhilHector I'm in New Zealand so it looks like I'm usually still sleeping when you're awake doing things. :)

**Comment by AkhilHector** [comment]
@chilts ah so sorry for troubling you, can you say me when are you available on irc ? What time would be comfortable for you ?

**Comment by AkhilHector** [comment]
@chilts If you had observed the commits i have done implementing the logger but before i could submit a pr it has been done. Should i work on it more or is there another open issue waiting for me.
