### ISSUE TITLE
PasswordChangeToken should support an email.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-db-mysql#58]
From https://github.com/mozilla/fxa-auth-server/pull/876/files#r32576784, this would enable the `/password/change/finish` endpoint to send a notification email with one fewer database hits.

**Comment by chilts** [comment]
Two PRs for the backend repos:

* https://github.com/mozilla/fxa-auth-db-mysql/pull/59
* https://github.com/mozilla/fxa-auth-db-mem/pull/37

Once they are merged, I'll PR this branch in the db-server for the tests to check they're being returned okay: https://github.com/chilts/fxa-auth-db-server/tree/return-email-on-passwordchangetoken
