### ISSUE TITLE
errors when running `npm test` locally.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-db-mysql#6]
> ➜  fxa-auth-db-mysql git:(master) npm test

```
> fxa-auth-db-mysql@0.0.0 test /Users/stomlinson/development/fxa-auth-db-mysql
> grunt && node ./bin/db_patcher.js >/dev/null &&  ./scripts/tap-coverage.js test/backend test/local

Running "jshint:files" (jshint) task
>> 23 files lint free.

Running "copyright:app" (copyright) task

Running "copyright:tests" (copyright) task

Done, without errors.
{"name":"db-patcher","hostname":"Shanes-Retina-MBP.local","pid":81159,"level":30,"msg":"Database patched to level 7","time":"2015-02-04T17:05:57.347Z","v":0}
ok test/backend/db_tests.js ......................... 135/135
404 '/account/hello-world'
404 '/emailRecord/3639623637316162613462663936643435396238393936393935373631646165406578616d706c652e636f6d'
404 '/sessionToken/0df4ec7f3dbea05cf365ac9b9f62b645cb52ed630c452b73a48797ad08585e6c'
404 '/sessionToken/0df4ec7f3dbea05cf365ac9b9f62b645cb52ed630c452b73a48797ad08585e6c'
404 '/keyFetchToken/3bde20c4ac621055d0e37c1e798fa4b1395d35a1b1aadd55155f37520cedc63a'
404 '/keyFetchToken/3bde20c4ac621055d0e37c1e798fa4b1395d35a1b1aadd55155f37520cedc63a'
404 '/accountResetToken/0ec2d9f2c6f9807d600fb49bd85940828b6b98abf3409d096ee71a23db3e9b73'
404 '/accountResetToken/0ec2d9f2c6f9807d600fb49bd85940828b6b98abf3409d096ee71a23db3e9b73'
404 '/passwordChangeToken/e4128f89d8f515f17ddbfb02cb803baedf282951a6bbe5e50aae8ea33849f528'
404 '/passwordChangeToken/e4128f89d8f515f17ddbfb02cb803baedf282951a6bbe5e50aae8ea33849f528'
404 '/passwordForgotToken/42985d3970a2a9608d2eb90b07b2632a71d151659c84a0d154344bb365b82e90'
404 '/passwordForgotToken/42985d3970a2a9608d2eb90b07b2632a71d151659c84a0d154344bb365b82e90'
404 '/passwordForgotToken/b080f8dcf51095cafad246807469f47e33b488506c2b899c5e47f7b6cf47ed51'
ok test/backend/remote.js ........................... 128/128
ok test/local/incorrect-patch-level.js .................. 4/4
{"name":"db-api","hostname":"Shanes-Retina-MBP.local","pid":81165,"level":30,"op":"MySql.connect","patchLevel":7,"patchLevelRequired":7,"msg":"","time":"2015-02-04T17:05:59.487Z","v":0}
ok test/local/log-stats.js .............................. 5/5
not ok test/local/mysql_tests.js ...................... 32/34
    Command: "/Users/stomlinson/development/nvm/v0.10.25/bin/node mysql_tests.js"
    TAP version 13
    ok 1 Got the ping ok
    ok 2 we have an error
    ok 3 should be equal
    ok 4 should be equal
    ok 5 should be equal
    ok 6 should be equal
    ok 7 we have an error
    ok 8 should be equal
    ok 9 should be equal
    ok 10 should be equal
    ok 11 should be equal
    ok 12 we have an error
    ok 13 should be equal
    ok 14 should be equal
    ok 15 should be equal
    ok 16 should be equal
    ok 17 we got an error
    ok 18 should be equal
    ok 19 should be equal
    ok 20 should be equal
    ok 21 should be equal
    ok 22 we got an error
    ok 23 should be equal
    ok 24 should be equal
    ok 25 should be equal
    ok 26 should be equal
    ok 27 the function was retried
    ok 28 Drop procedure was successful
    ok 29 The stored procedure creation was successful
    ok 30 The call to the stored procedure failed as expected
    not ok 31 error stringified is correct
      ---
        file:   /Users/stomlinson/development/fxa-auth-db-mysql/node_modules/bluebird/js/main/util.js
        line:   43
        column: 21
        stack:
          - |
            getCaller (/Users/stomlinson/development/fxa-auth-db-mysql/node_modules/tap/lib/tap-assert.js:418:17)
          - |
            assert (/Users/stomlinson/development/fxa-auth-db-mysql/node_modules/tap/lib/tap-assert.js:21:16)
          - |
            Function.equal (/Users/stomlinson/development/fxa-auth-db-mysql/node_modules/tap/lib/tap-assert.js:162:10)
          - |
            Test._testAssert [as equal] (/Users/stomlinson/development/fxa-auth-db-mysql/node_modules/tap/lib/tap-test.js:87:16)
          - |
            /Users/stomlinson/development/fxa-auth-db-mysql/test/local/mysql_tests.js:204:17
          - |
            tryCatch1 (/Users/stomlinson/development/fxa-auth-db-mysql/node_modules/bluebird/js/main/util.js:43:21)
          - |
            Promise$_callHandler [as _callHandler] (/Users/stomlinson/development/fxa-auth-db-mysql/node_modules/bluebird/js/main/promise.js:627:13)
          - |
            Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/Users/stomlinson/development/fxa-auth-db-mysql/node_modules/bluebird/js/main/promise.js:641:18)
          - |
            Promise$_settlePromiseAt [as _settlePromiseAt] (/Users/stomlinson/development/fxa-auth-db-mysql/node_modules/bluebird/js/main/promise.js:800:14)
          - |
            Promise$_settlePromises [as _settlePromises] (/Users/stomlinson/development/fxa-auth-db-mysql/node_modules/bluebird/js/main/promise.js:934:14)
        found:  |
          Error: ER_NO_DEFAULT_FOR_FIELD
        wanted: |
          Error: ER_BAD_NULL_ERROR
        diff:   |
          FOUND:  Error: ER_NO_DEFAULT_FOR_FIELD
          WANTED: Error: ER_BAD_NULL_ERROR
                            ^ (at position = 10)
      ...
    ok 32 error code is correct
    not ok 33 error errno is correct
      ---
        file:   /Users/stomlinson/development/fxa-auth-db-mysql/node_modules/bluebird/js/main/util.js
        line:   43
        column: 21
        stack:
          - |
            getCaller (/Users/stomlinson/development/fxa-auth-db-mysql/node_modules/tap/lib/tap-assert.js:418:17)
          - |
            assert (/Users/stomlinson/development/fxa-auth-db-mysql/node_modules/tap/lib/tap-assert.js:21:16)
          - |
            Function.equal (/Users/stomlinson/development/fxa-auth-db-mysql/node_modules/tap/lib/tap-assert.js:162:10)
          - |
            Test._testAssert [as equal] (/Users/stomlinson/development/fxa-auth-db-mysql/node_modules/tap/lib/tap-test.js:87:16)
          - |
            /Users/stomlinson/development/fxa-auth-db-mysql/test/local/mysql_tests.js:206:17
          - |
            tryCatch1 (/Users/stomlinson/development/fxa-auth-db-mysql/node_modules/bluebird/js/main/util.js:43:21)
          - |
            Promise$_callHandler [as _callHandler] (/Users/stomlinson/development/fxa-auth-db-mysql/node_modules/bluebird/js/main/promise.js:627:13)
          - |
            Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/Users/stomlinson/development/fxa-auth-db-mysql/node_modules/bluebird/js/main/promise.js:641:18)
          - |
            Promise$_settlePromiseAt [as _settlePromiseAt] (/Users/stomlinson/development/fxa-auth-db-mysql/node_modules/bluebird/js/main/promise.js:800:14)
          - |
            Promise$_settlePromises [as _settlePromises] (/Users/stomlinson/development/fxa-auth-db-mysql/node_modules/bluebird/js/main/promise.js:934:14)
        found:  1364
        wanted: 1048
      ...
    ok 34 test/local/mysql_tests.js

    1..34
    # tests 34
    # pass  32
    # fail  2

ok test/local/prune_tokens.js ......................... 11/11
total ............................................... 315/317

not ok
code coverage: 92.7%
generating coverage.html: complete in 0.4s
npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
➜  fxa-auth-db-mysql git:(master)
```
The sha is 1fcf15c1e60877623345109fa420124feee2f7c4

I'm sure this is operator error, but I haven't figured out where I am going wrong.

**Comment by jrgm** [comment]
Can you show me:

1. mysql -uUSER -pPASS -e 'show variables like "version"'
2. mysql -uUSER -pPASS -e 'show create table accounts' fxa

**Comment by chilts** [comment]
I have noticed sometimes that MySql might vary what errors it returns if the user and/or permissions are slightly different. Perhaps this is a variation here.

Am just gonna type a quick brain dump in case any of it helps. In general the dev user connects to mysql as 'root' so that (i) it has permissions for everything, so (2) can go ahead and create the database, tables and stored procedures without anything getting in the way. This means that all objects are also owned by root as well. Not sure if that matches your setup or if you're connecting (in the tests) as a different user.

Side note: in the (nearish) future we may end up with an `fxa` user which only has permissions to call various stored procedures and no direct access to the tables. In my WIP branch to add this I had to connect to the database as both the fxa user and the root user to test all of these scenarios out, and yes, due to the fact that the permissions were slightly different, the errors that came back were also slightly different. This isn't relevant here, but backs up the claim to just check who owns all those things.

**Comment by shane-tomlinson** [comment]
@jrgm 

> ➜  fxa-content-server git:(master) ✗ mysql -uroot -pXXXX -e 'show variables like "version"'
> Warning: Using a password on the command line interface can be insecure.
> +---------------+--------+
> | Variable_name | Value  |
> +---------------+--------+
> | version       | 5.6.16 |
> +---------------+--------+


> ➜  fxa-content-server git:(master) ✗ mysql -uroot -pXXXX -e 'show create table accounts' fxa
> Warning: Using a password on the command line interface can be insecure.
>+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
> | Table    | Create Table                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
> +----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
> | accounts | CREATE TABLE `accounts` (
>  `uid` binary(16) NOT NULL,
>  `normalizedEmail` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
>  `email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
>  `emailCode` binary(16) NOT NULL,
>  `emailVerified` tinyint(1) NOT NULL DEFAULT '0',
>  `kA` binary(32) NOT NULL,
>  `wrapWrapKb` binary(32) NOT NULL,
>  `authSalt` binary(32) NOT NULL,
>  `verifyHash` binary(32) NOT NULL,
>  `verifierVersion` tinyint(3) unsigned NOT NULL,
>  `verifierSetAt` bigint(20) unsigned NOT NULL,
>  `createdAt` bigint(20) unsigned NOT NULL,
>  `locale` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
>  PRIMARY KEY (`uid`),
>  UNIQUE KEY `normalizedEmail` (`normalizedEmail`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci |+----------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
> ➜  fxa-content-server git:(master) ✗

**Comment by jrgm** [comment]
@shane-tomlinson - hrm. So I was figuring the table schema was incorrect, but it looks right. Perhaps look into what @chilts noted about permissions. Or maybe rebuild the table with 

`rename table accounts to accountswtf; create table accounts as select * from accountswtf;`

**Comment by chilts** [comment]
@shane-tomlinson is this still the case? or is it still relevant to your work?

**Comment by shane-tomlinson** [comment]
This is no longer a problem. The issue was user permissions related IIRC.
