### ISSUE TITLE
Run mem backend tests on travis, as well as mysql tests

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-db-mysql#66]
This is a follow-up to #56

**Comment by philbooth** [comment]
After that, might we also consider deleting the `fxa-auth-db-server` repo, renaming this repo to `fxa-auth-db-server` and changing the sub-directory named `fxa-auth-db-server` to something else?

My thinking is that the mysqlness of this repo is both an implementation detail and not true when testing against `db-mem`. There's also a weird (imho) back-to-frontness about the server bit being a child of the actual database bit.

The server is the outwardly-visible interface that everything else cares about, why should it live tucked away as a child of the bit that nobody else interacts with directly?
