### ISSUE TITLE
Rename this repo

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-db-mysql#68]
Might we consider deleting the `fxa-auth-db-server` repo, renaming this repo to `fxa-auth-db-server` and re-jiggling the directory structure / dependencies to eliminate the `fxa-auth-db-server` sub-directory?

My thinking is that the mysqlness of this repo is both an implementation detail and not true when testing against `db-mem`.

There's also a weird (imho) back-to-frontness about the server bit being a child of the actual database bit. The server is the outwardly-visible interface that everything else cares about, why should it live tucked away as a child of the bit that nobody interacts with directly?

And all of our other services are named `fxa-xxx-server` so this one is going to seem pretty odd to people not familiar with the history.

Not to mention the fact that [Shane's amazing high-level architecture diagram](http://fxa.readthedocs.org/en/latest/#code) is now WRONG! :scream_cat:

I guess an argument could be made that it's just a name and names don't matter, but I kind of think it does in this case.

**Comment by rfk** [comment]
Yes we should, but we'll have to do it carefully because this repo name is baked into some ops config and deployment scripts.

**Comment by rfk** [comment]
@jrgm says the rename shouldn't be that big a deal since most stuff is till named "fxa-auth-db-server" in production config.

**Comment by philbooth** [comment]
Now that I have the [missing context](https://github.com/mozilla/fxa-auth-db-mysql/pull/70#issuecomment-125928574) for why things are like they are, I'm totes not bothered about this any more. :nail_care:

I'd even say it seems more proper to retain the `-mysql` suffix actually.
