### ISSUE TITLE
Gather and emit multi-device metrics

### ISSUE THREAD

**Issue by rfk** [mozilla/fxa-auth-db-mysql#72]
Once we have https://github.com/mozilla/fxa-auth-server/issues/983 and https://github.com/mozilla/fxa-auth-server/issues/988, we'll be able to make a pretty accurate assessment of "number of users with multiple devices connected".  I'm hoping that we can efficiently pull this out of the database on a daily basis and add it onto our dashboards.

We currently emit some daily metrics reports via the script here:

  https://github.com/mozilla-services/puppet-config/blob/master/fxa/modules/fxa_admin/files/gather_basic_metrics.py

But I think that logic should live over here next to the code, and should probably grow some tests etc eventually.  Perhaps we can do that move as part of this work.

Anyway, to the existing "count of all accounts" and "count of verified accounts", let's add "count of users with 2 or more devices" and "count of users with 3 or more devices".  

We'll need to use the `sessionTokens` table for this, and we should probably exclude sessions that haven't been active in the last month.  So the thing we want is "number of uids that have more than X sessionTokens that were active in the last month".

There's an index on `uid` so I'm hoping we can do it with an efficient SQL query, but my SQL-fu is not super strong.  It'll be something like this totally-untested SQL:

```
SELECT COUNT(uid) FROM (
    SELECT uid FROM sessionTokens
    GROUP BY uid
    HAVING COUNT(tokenId) > 1
)
```

But we'd have to check whether it can be run efficiently enough that we're happy doing it on our production db on a daily basis.

**Comment by rfk** [comment]
Also to note, we can and should start this without having explicit "device ids" like we'll get out of  mozilla/fxa-auth-server#988, just by counting each sessionToken as a separate device.  We'll over-estimate the number of multi-device users but hopefully not by much.  When device-id support propagates out to most of our clients, we can start counting only the sessionToken rows that have a device id.

**Comment by rfk** [comment]
@philbooth I added you to a team with read access to the above-linked repo, let me know if you still can't get to it.

**Comment by philbooth** [comment]
Thanks @rfk.

I'm starting work on this in earnest now, having digested all of the metrics context I was missing previously.

Regarding:

> ...that logic should live over here next to the code, and should probably grow some tests etc eventually. Perhaps we can do that move as part of this work.

I'm up for doing this, just want to be totally explicit and check whether my intentions are correct:

* These queries will be stored procedures in the database and exposed by the db-server API, yes?
* The queries can all go into the same commit, right? (e.g. `'feat(db): add queries for metrics reporting'` rather than separate commits naming each one)

**Comment by philbooth** [comment]
Bonus question:

* What do you want the path to look like for metrics requests? Are the following okay?

```
GET /metrics/countAccountsCreatedBefore
GET /metrics/countVerifiedAccountsCreatedBefore
GET /metrics/countMultiDeviceAccounts
GET /metrics/countMobileDeviceAccounts
```

**Comment by rfk** [comment]
> These queries will be stored procedures in the database

Likely yes, although we don't *have* to do it that way if it turns out to be a pain.  An initial version could just be a separate script in this repo that does the queries and spits out the results in the same way as the existing script.  That's harder to test though.

>  and exposed by the db-server API, yes?

I suggest that we treat this as an extra API specific to the mysql backend to begin with, and don't expose it as a general API that all backends should implement.  See for example the existing "getUnpublishedEvents" stuff that's also specific to the mysql backend.

> The queries can all go into the same commit, right?

Yes, absolutely.

**Comment by philbooth** [comment]
They can't be PR'd until #79 has been deployed to production but, for the record, I have [a branch](https://github.com/mozilla-services/puppet-config/compare/master...philbooth:fxa-multi-device-accounts?expand=1) with the (untested) `puppet-config` changes to use these stored procedures.

I'll keep it updated in-line with any code review changes that come up for #79.

**Comment by jrgm** [comment]
Sorry, late to this discussion, but I have a few comments, mostly contrary:

1. I do not think these queries belong in fxa-auth-db-mysql. These are purely backend metrics gathering queries, and have nothing to do with the other queries exposed via the rest API. 

2. There should be a separate mysql account that has limited (no-write) privileges, which will make it possible to audit these queries (which we don't do right now but should). The credentials for this account will never be exposed on a public web server.

3. Given (2), using stored procedures provides no value.

4. We should maybe work out a way to run these queries on a replicant of the master database. 

5. Some of the queries in the PR https://github.com/mozilla/fxa-auth-db-mysql/issues/72 look potentially punishing on production, in particular the sub-selects which do not have a great reputation in mysql, but perhaps that has improved in recent versions.

**Comment by philbooth** [comment]
Just on points `1` and `5` quickly:

> I do not think these queries belong in fxa-auth-db-mysql.

Imho, there is value in keeping all of the queries in one place as it reduces the likelihood of them breaking when new database migrations are added.

Out of sight and out of mind, queries in other repos are easily overlooked when making changes and, even worse do not have test coverage to alert us when they get broken. Hopefully such a bug would get noticed by people eyeballing the graphs, but things are already broken by that point.

> Some of the queries in the PR #72 look potentially punishing on production...

I'd like to run some performance tests and then report back to you guys, but I don't have connection details for the stage database that you mentioned in https://github.com/mozilla/fxa-auth-db-mysql/pull/79#issuecomment-131672342. Maybe we could talk later about whether/how I can access it and, if so, when to schedule it so as not to affect anyone else?

**Comment by rfk** [comment]
>  I do not think these queries belong in fxa-auth-db-mysql.

I ecourged @philbooth to put them here for exactly the reasons he described - as core product success metics, ISTM there's value in maintaining and testing there here alongside the rest of the code to make sure they're tracking the things we want.  But if they'll work better operationally when located elsewhere, 

> There should be a separate mysql account that has limited (no-write) privileges, which will make it possible to audit these queries

:+1: 

> Some of the queries in the PR #72 look potentially punishing on production

Yep; I'm hoping we can make them work by dialing down the isolation level to avoid taking locks, but I can easily imagine MySQL doing something stupid here like reifying the entire sub-select result as a temporary table.

**Comment by rfk** [comment]
> We should maybe work out a way to run these queries on a replicant of the master database. 

Is there an existing replica that we might use for this purpose, without breaking the replication?

**Comment by jrgm** [comment]
> I'd like to run some performance tests and then report back to you guys, but I don't have connection details for the stage database that you mentioned in #79 (comment). Maybe we could talk later about whether/how I can access it and, if so, when to schedule it so as not to affect anyone else?

So, to start file a PR like https://github.com/mozilla-services/puppet-config/pull/1401/files and then I'll ask whd about the rest that he has to do.

**Comment by jrgm** [comment]
> Is there an existing replica that we might use for this purpose, without breaking the replication?

There is replica, but it's not currently setup security-wise for access (I can't run queries there either).

**Comment by jrgm** [comment]
> I ecourged @philbooth to put them here for exactly the reasons he described - as core product success metics, ISTM there's value in maintaining and testing there here alongside the rest of the code to make sure they're tracking the things we want. But if they'll work better operationally when located elsewhere,

Yeah, sure. I can see that partly, but it seems we are expanding the surface of this surface, ironically by using even more stored procedures, and mixing on-demand with background tasks, when there is compelling benefit.

**Comment by rfk** [comment]
>  mixing on-demand with background tasks 

There's some prior art here in the token-pruning stuff, which lives in this repo and runs as a background task.

I agree though that your points (2) and (3) argue against using stored procedures for this.  It may be simpler to start with a separate script that runs the queries in much the same way as [1], but lives in this repo and can be tested alongside it.

[1] https://github.com/mozilla-services/puppet-config/blob/master/fxa/modules/fxa_admin/files/gather_basic_metrics.py

**Comment by philbooth** [comment]
> It may be simpler to start with a separate script that runs the queries in much the same way as [1], but lives in this repo and can be tested alongside it.

I'm totes cool with adopting that approach. Have a few questions but I'll ask them in our 1:1.

**Comment by philbooth** [comment]
@jrgm, quick question regarding this separate script approach: Is it okay from an ops perspective if it's a node script? Any hidden gotchas relating to production environments on that front?

Just want to be sure I'm not going down any blind alleys before I start on it. :)

**Comment by philbooth** [comment]
> So, to start file a PR like https://github.com/mozilla-services/puppet-config/pull/1401/files and then I'll ask whd about the rest that he has to do.

FYI: https://github.com/mozilla-services/puppet-config/pull/1496

**Comment by philbooth** [comment]
Few more questions about the standalone script approach, @jrgm or @rfk:

* If a node script is okay, is it also okay for it to `require` other modules from this project, or does it need to be genuinely standalone?

* The existing python script reads from `/etc/gather_basic_metrics.conf` and writes to `/media/ephemeral0/fxa-admin/basic_metrics.log`. Will the new script be running from the same context as the existing one, i.e. should it use the same paths?

* If the answer to both of the preceding questions is *yes*, would it be desirable to move those hard-coded paths into this project's config settings?

**Comment by jrgm** [comment]
> @jrgm, quick question regarding this separate script approach: Is it okay from an ops perspective if it's a node script? 

Yes, that's fine.

> Any hidden gotchas relating to production environments on that front?

Not that I can think of. nodejs 0.10.

**Comment by jrgm** [comment]
> If a node script is okay, is it also okay for it to require other modules from this project, or does it need to be genuinely standalone?

Yeah, so I suppose it would be a deploy on the admin server that doesn't actually run the server (not reachable from the web anyways).

> The existing python script reads from /etc/gather_basic_metrics.conf and writes to /media/ephemeral0/fxa-admin/basic_metrics.log. Will the new script be running from the same context as the existing one, i.e. should it use the same paths?

Yes. @whd asked to use mozlog for logging, which is the logger that's in fxa-auth-db-mysql.

> If the answer to both of the preceding questions is yes, would it be desirable to move those hard-coded paths into this project's config settings?

So, logging should go to that same media/ephemeral location. The config flle, you should assume it is somewhere that will be passed to the program. It has credentials that are managed by puppet on that box. It's current format is a python config format, but we could make it available in json if you want.
