### ISSUE TITLE
Implement endpoint and query for retention metrics

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-db-mysql#75]
The requirement for this comes from https://github.com/mozilla/fxa/issues/45, which describes a user retention curve with points plotted at days 0, 1, 3, 7, 14, 30, 60 and 90.

Day 0 will always be 100% and, in our case, represents all accounts that have a `lastAccessTime` set in the `sessionTokens` table. Statistically, we can't make comparisons against accounts without a qualifying session because we don't know how long those users were retained. Thus the graph will end up being populated gradually until it is fully available, 90 days after the deployment of https://github.com/mozilla/fxa-auth-server/issues/983.

The subsequent days represent the percentage of those users who were still active at that point and can be measured by comparing `lastAccessTime` to `createdAt` from the `accounts` table.

Concretely, this is the kind of thing I'm thinking of in SQL terms (although there may be a more performant way to do it):

```sql
SELECT
	COUNT(s0.lastAccessTime) AS d0,
	COUNT(s1.lastAccessTime) AS d1,
	COUNT(s3.lastAccessTime) AS d3,
	COUNT(s7.lastAccessTime) AS d7,
	COUNT(s14.lastAccessTime) AS d14,
	COUNT(s30.lastAccessTime) AS d30,
	COUNT(s60.lastAccessTime) AS d60,
	COUNT(s90.lastAccessTime) AS d90
FROM accounts AS a
	LEFT JOIN sessionTokens AS s0 ON a.uid = s0.uid
	LEFT JOIN sessionTokens AS s1 ON a.uid = s1.uid
	LEFT JOIN sessionTokens AS s3 ON a.uid = s3.uid
	LEFT JOIN sessionTokens AS s7 ON a.uid = s7.uid
	LEFT JOIN sessionTokens AS s14 ON a.uid = s14.uid
	LEFT JOIN sessionTokens AS s30 ON a.uid = s30.uid
	LEFT JOIN sessionTokens AS s60 ON a.uid = s60.uid
	LEFT JOIN sessionTokens AS s90 ON a.uid = s90.uid
WHERE
	s0.lastAccessTime > 0 AND
	s1.lastAccessTime >= a.createdAt + 86400000 AND
	s3.lastAccessTime >= a.createdAt + 259200000 AND
	s7.lastAccessTime >= a.createdAt + 604800000 AND
	s14.lastAccessTime >= a.createdAt + 1209600000 AND
	s30.lastAccessTime >= a.createdAt + 2592000000 AND
	s60.lastAccessTime >= a.createdAt + 5184000000 AND
	s90.lastAccessTime >= a.createdAt + 7776000000;
```

@ckarlof, mentioning you in case you want to speak about this on Thursday.

**Comment by philbooth** [comment]
Just realised there are a number of problems with that query. It counts sessions, not users, and `AND`ing the `WHERE` conditions like that won't do what I wanted.

Not sure what the correct way to do it in a single query is, but an example of what I really mean broken into separate queries would be:

```sql
-- account retention 0 day, express as 100%
SELECT COUNT(DISTINCT a.uid)
FROM accounts AS a
LEFT JOIN sessionTokens AS s
ON a.uid = s.uid
WHERE s.lastAccessTime > 0;

-- account retention 1 day, express as a percentage of 0 day
SELECT COUNT(DISTINCT a.uid)
FROM accounts AS a
LEFT JOIN sessionTokens AS s
ON a.uid = s.uid
WHERE s.lastAccessTime >= a.createdAt + 86400000;

-- account retention 3 day, express as a percentage of 0 day
SELECT COUNT(DISTINCT a.uid)
FROM accounts AS a
LEFT JOIN sessionTokens AS s
ON a.uid = s.uid
WHERE s.lastAccessTime >= a.createdAt + 259200000;
```

**Comment by ckarlof** [comment]
@philbooth Yes, let's discuss tomorrow. Depending on how we frame and scope this problem, I think it can grow beyond what we currently record in the Auth DB. For example, as framed in https://github.com/mozilla/fxa/issues/45#issuecomment-126813305, we would actually need to know if the user was active on each particular day, which is more than `lastAccessTime` can tell us.
