### ISSUE TITLE
Use new metrics script to feed FxA metrics dashboards

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-db-mysql#83]
This work will actually be done in [`mozilla-services/puppet-config`](https://github.com/mozilla-services/puppet-config), but I'm raising the issue here to give it visibility in our planning process.

Now that the new metrics script is in `master`, we need to update [the puppet manifest](https://github.com/mozilla-services/puppet-config/blob/master/fxa/modules/fxa_admin/manifests/basic_metrics.pp) to clone this repo and run the new script and then update [the Heka filter](https://github.com/mozilla-services/puppet-config/blob/master/shared/modules/fxa/files/hekad/lua_filters/fxa_basic_metrics.lua) to process the new metrics.

**Comment by rfk** [comment]
Calling it out in a comment in case it's not obvious from the issue activity log: this has been opened as a PR at https://github.com/mozilla-services/puppet-config/pull/1539

**Comment by rfk** [comment]
With apologies to @philbooth, I'm going to close out these long-blocked bugs.  Unfortunately we haven't been able to make this approach work in production, so let's take a step back and look at alternative ways to establish similar metrics (e.g. by leaning on new metrics pipleline work, to process account activity events to determine what devices were active on each day).
