### ISSUE TITLE
Implement device metrics dashboard

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-db-mysql#84]
This work will actually take place in [`mozilla/accounts-dashboard`](https://github.com/mozilla/accounts-dashboard) but I'm raising it here to give it visibility in our planning process.

We need to create new charts for the device metrics that we will soon be recording. To limit intrusiveness on other views, they should probably be grouped together into a new sub-dashboard for FxA.

**Comment by philbooth** [comment]
Adding a `blocked` label to this. The work is [here](https://github.com/mozilla/accounts-dashboard/compare/phil/devices-dashboard) but it depends on https://github.com/mozilla-services/puppet-config/pull/1539 before it can be reviewed.

**Comment by vladikoff** [comment]
needs a blocked label

**Comment by rfk** [comment]
With apologies to @philbooth, I'm going to close out these long-blocked bugs. Unfortunately we haven't been able to make this approach work in production, so let's take a step back and look at alternative ways to establish similar metrics (e.g. by leaning on new metrics pipleline work, to process account activity events to determine what devices were active on each day).

**Comment by rfk** [comment]
And no, I didn't purposely wait for @philbooth to be on PTO before doing so, I swear! :-)
