### ISSUE TITLE
Emit events for account activity on key days

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-db-mysql#85]
Part of https://github.com/mozilla/fxa/issues/45.

We need to emit events corresponding to activity on a given day for each account, to be processed by Heka as food for the retention graph.

**Comment by philbooth** [comment]
Raised this in the wrong repo, sigh. Pretend it's in `fxa-auth-server` .

**Comment by rfk** [comment]
> Raised this in the wrong repo,

I took the liberty of migrating it to https://github.com/mozilla/fxa-auth-server/issues/1027 :-)
