### ISSUE TITLE
Implement retention graph

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-auth-db-mysql#87]
Part of https://github.com/mozilla/fxa/issues/45.

This work will actually be done in [`mozilla/accounts-dashboard`](https://github.com/mozilla/accounts-dashboard), but I'm raising the issue here to give it visibility in our planning process.

When https://github.com/mozilla/fxa-auth-db-mysql/issues/86 is in place, we can implement the new retention graph plotting account activity at days 0, 1, 3, 7, 14, 30, 60 and 90.

**Comment by vladikoff** [comment]
@philbooth hey, let's chat about this in the next few days on Vidyo! :telephone_receiver:

**Comment by philbooth** [comment]
Sounds good @vladikoff. We can liaise in IRC but fwiw today I'm free all afternoon and evening (BST), tomorrow and Friday I'm free in the afternoon but not the evening.

**Comment by vladikoff** [comment]
### Draft 1
> this the plan we had initially, but have to remove Cassandra from it:

<img src="http://v14d.com/i/55fae562c3b46.jpg" width=550 />

### Draft 2:
<img src="http://v14d.com/i/55faede7ccd4e.jpg" width=650 />

**Comment by ckarlof** [comment]
I'm happy to see progress on this!

**Comment by vladikoff** [comment]
Blocked by https://bugzilla.mozilla.org/show_bug.cgi?id=1207015#c20

**Comment by vladikoff** [comment]
the basic account.signed event graph is complete and linked here: https://mana.mozilla.org/wiki/display/CLOUDSERVICES/Retention+Metrics

We can now proceed making other retention graphs
