### ISSUE TITLE
remove eslint complexity checks

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-db-mysql#95]
Running npm test on master produces this chirp. I don't think the linter complexity tests have ever uncovered  any real bugs, and mostly just whine about `||` defaulting. Can we remove the linting for "complexity"?

```
Running "eslint:files" (eslint) task

lib/db/mem.js
  306:34  warning  Function 'anonymous' has a complexity of 7  complexity

✖ 1 problem (0 errors, 1 warning)
```

**Comment by rfk** [comment]
:+1:

**Comment by TDA** [comment]
I can take this up :) @jrgm
